preserve_hierarchy: true
files:
  - source: /packages/yoroi-extension/app/i18n/locales/**/en-US.json
    translation: /packages/yoroi-extension/app/i18n/locales/**/%locale%.json
    languages_mapping:
      locale:
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        ja: ja-JP
        ko: ko-KR
        ru: ru-RU
        de: de-DE
        fr: fr-FR
        nl: nl-NL
        id: id-ID
        es: es-ES
        it: it-IT
        sk: sk-SK
        cs: cs-CZ
  - source: /packages/yoroi-extension/app/i18n/locales/**/en-US.md
    translation: /packages/yoroi-extension/app/i18n/locales/**/%locale%.md
    languages_mapping:
      locale:
        zh-CN: zh-Hans
        zh-TW: zh-Hant
        ja: ja-JP
        ko: ko-KR
        ru: ru-RU
        de: de-DE
        fr: fr-FR
        nl: nl-NL
        id: id-ID
        es: es-ES
        it: it-IT
        sk: sk-SK
        cs: cs-CZ
    content_segmentation: 0
