#!/bin/bash

RUST_TOOLCHAIN="1.32.0"

set +e
pushd wallet-wasm
rustup install ${RUST_TOOLCHAIN} && \
rustup target add --toolchain ${RUST_TOOLCHAIN} wasm32-unknown-unknown && \
cargo  +${RUST_TOOLCHAIN} build --target wasm32-unknown-unknown --release --verbose && \
popd && \
npm run build
