#!/bin/bash

RUST_TOOLCHAIN="nightly"

set +e
pushd wallet-wasm
rustup target add --toolchain ${RUST_TOOLCHAIN} wasm32-unknown-unknown && \
cargo  +${RUST_TOOLCHAIN} build --target wasm32-unknown-unknown --release --verbose && \
popd && \
npm run build
