export const mockReviewTX = {
  inputs: [
    {
      address: 'addr1q822spx8lcgvga4vgl3khtsl6ulk679csyl6swhn4p2jdy6s27v5vqkrt30n773669yeynnxkdh0pdytv57t296pn4qqgfgjhd',
      addressKind: 0,
      assets: [
        {
          isPrimary: true,
          label: '1.000000 ADA',
          name: 'ADA',
          quantity: '1000000',
          tokenInfo: {
            application: 'coin',
            decimals: 6,
            description: 'Cardano',
            fingerprint: '',
            id: '.',
            name: 'ADA',
            nature: 'primary',
            originalImage: '',
            reference: '',
            status: 'valid',
            symbol: '₳',
            tag: '',
            ticker: 'ADA',
            type: 'ft',
            website: 'https://www.cardano.org/',
          },
        },
        {
          isPrimary: false,
          label: '1223.000000 SHIBA',
          name: 'SHIBA',
          quantity: '1223.000000',
          tokenInfo: {
            application: 'coin',
            decimals: 6,
            description: 'Cardano',
            fingerprint: '',
            id: '.',
            name: 'SHIBA',
            nature: 'primary',
            originalImage: '',
            reference: '',
            status: 'valid',
            symbol: 'SHIB',
            tag: '',
            ticker: 'SHIBA',
            type: 'ft',
            website: 'https://www.SHIBA.org/',
          },
        },
      ],
      ownAddress: true,
      rewardAddress: 'stake1u9g90x2xqtp4chel0gadzjvjfentxmhskj9k2094zaqe6sqws75rv',
      txHash: '4d8a344397a40b30cdefe66ee72c7a8b3aba416e07d6bd86b28db06528672c8c',
      txIndex: 2,
    },
    {
      address: 'addr1q822spx8lcgvga4vgl3khtsl6ulk679csyl6swhn4p2jdy6s27v5vqkrt30n773669yeynnxkdh0pdytv57t296pn4qqgfgjhd',
      addressKind: 0,
      assets: [
        {
          isPrimary: false,
          label: '1223.000000 SHIBA',
          name: 'SHIBA',
          quantity: '1223.000000',
          tokenInfo: {
            application: 'coin',
            decimals: 6,
            description: 'Cardano',
            fingerprint: '',
            id: '.',
            name: 'SHIBA',
            nature: 'primary',
            originalImage: '',
            reference: '',
            status: 'valid',
            symbol: 'SHIB',
            tag: '',
            ticker: 'SHIBA',
            type: 'ft',
            website: 'https://www.SHIBA.org/',
          },
        },
      ],
      ownAddress: true,
      rewardAddress: 'stake1u9g90x2xqtp4chel0gadzjvjfentxmhskj9k2094zaqe6sqws75rv',
      txHash: '4d8a344397a40b30cdefe66ee72c7a8b3aba416e07d6bd86b28db06528672c8c',
      txIndex: 3,
    },
    {
      address: 'addr1q822spx8lcgvga4vgl3khtsl6ulk679csyl6swhn4p2jdy6s27v5vqkrt30n773669yeynnxkdh0pdytv57t296pn4sdfasdsda',
      addressKind: 0,
      assets: [],
      ownAddress: true,
      rewardAddress: 'stake1u9g90x2xqtp4chel0gadzjvjfentxmhskj9k2094zaqe6sqws75rv',
      txHash: '4d8a344397a40b30cdefe66ee72c7a8b3aba416e07d6bd86b28db06528672c8c',
      txIndex: 3,
    },
  ],
  outputs: [
    {
      assets: [
        {
          tokenInfo: {
            id: '.',
            nature: 'primary',
            type: 'ft',
            application: 'coin',
            fingerprint: '',
            status: 'valid',
            decimals: 6,
            name: 'ADA',
            ticker: 'ADA',
            symbol: '₳',
            reference: '',
            tag: '',
            website: 'https://www.cardano.org/',
            originalImage: '',
            description: 'Cardano',
          },
          name: 'ADA',
          label: '1.826447 ADA',
          quantity: '1826447',
          isPrimary: true,
        },
      ],
      address: 'addr1q8afnth730r7u9v568qnqdtsp6du9ay6766h4gy6uhkdckzs27v5vqkrt30n773669yeynnxkdh0pdytv57t296pn4qq726e0s',
      addressKind: 0,
      rewardAddress: 'stake1u9g90x2xqtp4chel0gadzjvjfentxmhskj9k2094zaqe6sqws75rv',
      ownAddress: true,
    },
  ],
  fee: {
    tokenInfo: {
      id: '.',
      nature: 'primary',
      type: 'ft',
      application: 'coin',
      fingerprint: '',
      status: 'valid',
      decimals: 6,
      name: 'ADA',
      ticker: 'ADA',
      symbol: '₳',
      reference: '',
      tag: '',
      website: 'https://www.cardano.org/',
      originalImage: '',
      description: 'Cardano',
    },
    name: 'ADA',
    label: '0.173553 ADA',
    quantity: '173553',
    isPrimary: true,
  },
  certificates: [
    {
      type: 'VoteDelegation',
      value: {
        stake_credential: {
          Key: '5057994602c35c5f3f7a3ad149924e66b36ef0b48b653cb517419d40',
        },
        drep: 'AlwaysNoConfidence',
      },
    },
  ],
  mint: null,
  referenceInputs: [
    {
      assets: [
        {
          tokenInfo: {
            id: '.',
            nature: 'primary',
            type: 'ft',
            application: 'coin',
            fingerprint: '',
            status: 'valid',
            decimals: 6,
            name: 'ADA',
            ticker: 'ADA',
            symbol: '₳',
            reference: '',
            tag: '',
            website: 'https://www.cardano.org/',
            originalImage: '',
            description: 'Cardano',
          },
          name: 'ADA',
          label: '1.000000 ADA',
          quantity: '1000000',
          isPrimary: true,
        },
      ],
      address: 'addr1q822spx8lcgvga4vgl3khtsl6ulk679csyl6swhn4p2jdy6s27v5vqkrt30n773669yeynnxkdh0pdytv57t296pn4qqgfgjhd',
      addressKind: 0,
      rewardAddress: 'stake1u9g90x2xqtp4chel0gadzjvjfentxmhskj9k2094zaqe6sqws75rv',
      ownAddress: true,
      txIndex: 2,
      txHash: '4d8a344397a40b30cdefe66ee72c7a8b3aba416e07d6bd86b28db06528672c8c',
    },
    {
      assets: [
        {
          tokenInfo: {
            id: '.',
            nature: 'primary',
            type: 'ft',
            application: 'coin',
            fingerprint: '',
            status: 'valid',
            decimals: 6,
            name: 'ADA',
            ticker: 'ADA',
            symbol: '₳',
            reference: '',
            tag: '',
            website: 'https://www.cardano.org/',
            originalImage: '',
            description: 'Cardano',
          },
          name: 'ADA',
          label: '1.000000 ADA',
          quantity: '1000000',
          isPrimary: true,
        },
      ],
      address: 'addr1q822spx8lcgvga4vgl3khtsl6ulk679csyl6swhn4p2jdy6s27v5vqkrt30n773669yeynnxkdh0pdytv57t296pn4qqgfgjhd',
      addressKind: 0,
      rewardAddress: 'stake1u9g90x2xqtp4chel0gadzjvjfentxmhskj9k2094zaqe6sqws75rv',
      ownAddress: true,
      txIndex: 3,
      txHash: '4d8a344397a40b30cdefe66ee72c7a8b3aba416e07d6bd86b28db06528672c8c',
    },
  ],
};
