// flow-typed signature: 33fa372c8b2fe8281d3e872a56771a41
// flow-typed version: <<STUB>>/react-router_v6.23.0/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  

import type {
            ActionFunction,ActionFunctionArgs,Blocker,BlockerFunction,unstable_DataStrategyFunction,unstable_DataStrategyFunctionArgs,unstable_DataStrategyMatch,ErrorResponse,Fetcher,HydrationState,InitialEntry,JsonFunction,LazyRouteFunction,LoaderFunction,LoaderFunctionArgs,Location,Navigation,ParamParseKey,Params,Path,PathMatch,PathParam,PathPattern,RedirectFunction,RelativeRoutingType,Router as RemixRouter,FutureConfig as RouterFutureConfig,ShouldRevalidateFunction,ShouldRevalidateFunctionArgs,To,UIMatch,unstable_HandlerResult
            } from '@remix-run/router';
import {
            AbortedDeferredError,Action as NavigationType,createPath,defer,generatePath,isRouteErrorResponse,json,matchPath,matchRoutes,parsePath,redirect,redirectDocument,resolvePath
            } from '@remix-run/router';
import type {
            AwaitProps,FutureConfig,IndexRouteProps,LayoutRouteProps,MemoryRouterProps,NavigateProps,OutletProps,PathRouteProps,RouteProps,RouterProps,RouterProviderProps,RoutesProps
            } from './lib/components';
import {
            Await,MemoryRouter,Navigate,Outlet,Route,Router,RouterProvider,Routes,createRoutesFromChildren,renderMatches
            } from './lib/components';
import type {
            DataRouteMatch,DataRouteObject,IndexRouteObject,NavigateOptions,Navigator,NonIndexRouteObject,RouteMatch,RouteObject
            } from './lib/context';
import {
            DataRouterContext,DataRouterStateContext,LocationContext,NavigationContext,RouteContext
            } from './lib/context';
import type {
            NavigateFunction
            } from './lib/hooks';
import {
            useActionData,useAsyncError,useAsyncValue,useBlocker,useHref,useInRouterContext,useLoaderData,useLocation,useMatch,useMatches,useNavigate,useNavigation,useNavigationType,useOutlet,useOutletContext,useParams,useResolvedPath,useRevalidator,useRouteError,useRouteId,useRouteLoaderData,useRoutes,useRoutesImpl
            } from './lib/hooks';
declare type Hash = string;declare type Pathname = string;declare type Search = string;export type {
          ActionFunction,ActionFunctionArgs,AwaitProps,DataRouteMatch,DataRouteObject,unstable_DataStrategyFunction,unstable_DataStrategyFunctionArgs,unstable_DataStrategyMatch,ErrorResponse,Fetcher,FutureConfig,Hash,IndexRouteObject,IndexRouteProps,JsonFunction,LayoutRouteProps,LazyRouteFunction,LoaderFunction,LoaderFunctionArgs,Location,MemoryRouterProps,NavigateFunction,NavigateOptions,NavigateProps,Navigation,Navigator,NonIndexRouteObject,OutletProps,ParamParseKey,Params,Path,PathMatch,PathParam,PathPattern,PathRouteProps,Pathname,RedirectFunction,RelativeRoutingType,RouteMatch,RouteObject,RouteProps,RouterProps,RouterProviderProps,RoutesProps,Search,ShouldRevalidateFunction,ShouldRevalidateFunctionArgs,To,UIMatch,Blocker,BlockerFunction,unstable_HandlerResult
        }
declare export {
          AbortedDeferredError,Await,MemoryRouter,Navigate,NavigationType,Outlet,Route,Router,RouterProvider,Routes,createPath,createRoutesFromChildren,createRoutesFromChildren as createRoutesFromElements,defer,generatePath,isRouteErrorResponse,json,matchPath,matchRoutes,parsePath,redirect,redirectDocument,renderMatches,resolvePath,useBlocker,useActionData,useAsyncError,useAsyncValue,useHref,useInRouterContext,useLoaderData,useLocation,useMatch,useMatches,useNavigate,useNavigation,useNavigationType,useOutlet,useOutletContext,useParams,useResolvedPath,useRevalidator,useRouteError,useRouteLoaderData,useRoutes
        }
declare function mapRouteProperties(
route: RouteObject): { ...$Rest<RouteObject, {...}>,...{
hasErrorBoundary: boolean,...
} }
declare export function createMemoryRouter(
routes: RouteObject[],
opts?: {
basename?: string,
future?: $Rest<$Diff<RouterFutureConfig,{ "v7_prependBasename": any}>, {...}>,
hydrationData?: HydrationState,
initialEntries?: InitialEntry[],
initialIndex?: number,
unstable_dataStrategy?: unstable_DataStrategyFunction,...
}): RemixRouter
declare export {
          DataRouterContext as UNSAFE_DataRouterContext,DataRouterStateContext as UNSAFE_DataRouterStateContext,LocationContext as UNSAFE_LocationContext,NavigationContext as UNSAFE_NavigationContext,RouteContext as UNSAFE_RouteContext,mapRouteProperties as UNSAFE_mapRouteProperties,useRouteId as UNSAFE_useRouteId,useRoutesImpl as UNSAFE_useRoutesImpl
        }

}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router/dist' {
  declare module.exports: any;
}

declare module 'react-router/dist/main' {
  declare module.exports: any;
}

declare module 'react-router/dist/react-router.development' {
  declare module.exports: any;
}

declare module 'react-router/dist/react-router.production.min' {
  declare module.exports: any;
}

declare module 'react-router/dist/umd/react-router.development' {
  declare module.exports: any;
}

declare module 'react-router/dist/umd/react-router.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router/dist/index' {
  declare module.exports: $Exports<'react-router/dist'>;
}
declare module 'react-router/dist/index.js' {
  declare module.exports: $Exports<'react-router/dist'>;
}
declare module 'react-router/dist/main.js' {
  declare module.exports: $Exports<'react-router/dist/main'>;
}
declare module 'react-router/dist/react-router.development.js' {
  declare module.exports: $Exports<'react-router/dist/react-router.development'>;
}
declare module 'react-router/dist/react-router.production.min.js' {
  declare module.exports: $Exports<'react-router/dist/react-router.production.min'>;
}
declare module 'react-router/dist/umd/react-router.development.js' {
  declare module.exports: $Exports<'react-router/dist/umd/react-router.development'>;
}
declare module 'react-router/dist/umd/react-router.production.min.js' {
  declare module.exports: $Exports<'react-router/dist/umd/react-router.production.min'>;
}
