// @flow
export const SUPPORTED_CURRENCIES = [
  { symbol: 'USD' },
  { symbol: 'JPY' },
  { symbol: 'BGN' },
  { symbol: 'CZK' },
  { symbol: 'DKK' },
  { symbol: 'GBP' },
  { symbol: 'HUF' },
  { symbol: 'PLN' },
  { symbol: 'RON' },
  { symbol: 'SEK' },
  { symbol: 'CHF' },
  { symbol: 'ISK' },
  { symbol: 'NOK' },
  { symbol: 'HRK' },
  { symbol: 'RUB' },
  { symbol: 'TRY' },
  { symbol: 'AUD' },
  { symbol: 'BRL' },
  { symbol: 'CAD' },
  { symbol: 'CNY' },
  { symbol: 'HKD' },
  { symbol: 'IDR' },
  { symbol: 'ILS' },
  { symbol: 'INR' },
  { symbol: 'KRW' },
  { symbol: 'MXN' },
  { symbol: 'MYR' },
  { symbol: 'NZD' },
  { symbol: 'PHP' },
  { symbol: 'SGD' },
  { symbol: 'THB' },
  { symbol: 'ZAR' },
];
