// @flow
export const RESTORE_WALLET_STEPS = Object.freeze({
  SELECT_WALLET_TYPE: 'SELECT_WALLET_TYPE',
  SAVE_RECOVERY_PHRASE: 'SAVE_RECOVERY_PHRASE',
  ADD_WALLET_DETAILS: 'ADD_WALLET_DETAILS',
});
