//  ==== Theme: Yoroi === //

export default {
  '--preferred-font': '"Times New Roman", serif',

  '--font-ultralight': 'SFUIDisplay-Ultralight',
  '--font-thin': 'SFUIDisplay-Thin',
  '--font-light': 'SFUIDisplay-Light',
  '--font-regular': 'SFUIDisplay-Regular',
  '--font-medium': 'SFUIDisplay-Medium',
  '--font-semibold': 'SFUIDisplay-Semibold',
  '--font-bold': 'SFUIDisplay-Bold',
  '--font-heavy': 'SFUIDisplay-Heavy',
  '--font-black': 'SFUIDisplay-Black',

  '--theme-input-hint-font': 'SFUIDisplay-Regular',

  '--theme-scrollbar-thumb-background': '#c8ccce',

  '--theme-autocomplete-bg-color': '#f3f3f5',
  '--theme-autocomplete-border': '1px solid #c6cdd6',
  '--theme-autocomplete-border-focus-color': '#121327',
  '--theme-autocomplete-search-color': '#121327',
  '--theme-autocomplete-placeholder-color': 'rgba(94, 96, 102, 0.5)',
  '--theme-autocomplete-selected-word-text-color': '#fafbfc',
  '--theme-autocomplete-selected-word-box-background-color': 'rgba(218, 164, 154, 1)',
  '--theme-autocomplete-suggestions-list-border-color': '#c6cdd6',
  '--theme-autocomplete-suggestions-list-item-bg-color': '#fafbfc',
  '--theme-autocomplete-suggestions-list-item-font-color': '#121327',
  '--theme-autocomplete-suggestions-list-item-highlight-color': '#edeeef',

  '--theme-bordered-box-background-color': '#f3f3f5',
  '--theme-bordered-box-border': '1px solid #f3f3f5',
  '--theme-bordered-box-text-color': '#121327',

  '--theme-button-primary-background-color': '#daa49a',
  '--theme-button-primary-background-color-hover': '#edb3a8',
  '--theme-button-primary-background-color-active': '#c4948b',
  '--theme-button-primary-background-color-disabled': 'rgba(218, 164, 154, 0.3)',
  '--theme-button-primary-text-color-disabled': '#fafbfc',
  '--theme-button-primary-text-color': '#fafbfc',

  '--theme-button-flat-background-color': 'rgba(218, 164, 154, 0.1)',
  '--theme-button-flat-background-color-hover': 'rgba(242, 183, 172, 0.1)',
  '--theme-button-flat-background-color-active': 'rgba(191, 144, 136, 0.1)',
  '--theme-button-flat-background-color-disabled': 'rgba(240, 243, 245, 0.3)',
  '--theme-button-flat-text-color-disabled': '#121327',
  '--theme-button-flat-text-color': '#121327',

  '--theme-checkbox-label-color': '#121327',
  '--theme-checkbox-border-color': '#daa49a',
  '--theme-checkbox-background-color-checked': '#daa49a',

  '--theme-select-arrow-color': '#c6cdd6',
  '--theme-select-arrow-color-open': '#121327',
  '--theme-select-background-color': '#fafbfc',
  '--theme-select-option-highlight-color': '#edeeef',
  '--theme-select-option-text-color': '#121327',
  '--theme-select-options-border-color': '#c6cdd6',
  '--theme-select-options-shadow': 'none',

  '--theme-choice-tabs-text-color': '#121327',
  '--theme-choice-tabs-text-color-active': '#121327',
  '--theme-choice-tabs-bottom-border-color-active': '#121327',

  '--theme-dialog-choice-tabs-text-color': '#121327',
  '--theme-dialog-choice-tabs-text-color-active': '#121327',
  '--theme-dialog-choice-tabs-bottom-border-color-active': '#121327',
  '--theme-dialog-big-button-background-color': '#f3f3f5',
  '--theme-dialog-big-button-border-color': '#f3f3f5',
  '--theme-dialog-big-button-label-color': '#121327',
  '--theme-dialog-big-button-description-color': '#121327',
  '--theme-dialog-title-color': '#121327',

  '--theme-input-border-color': '#c6cdd6',
  '--theme-input-label-color': '#121327',
  '--theme-input-text-color': '#121327',
  '--theme-input-right-floating-text-color': 'rgba(94, 96, 102, 0.5)',
  '--theme-input-placeholder-color': 'rgba(94, 96, 102, 0.5)',
  '--theme-input-error-color': '#ea4c5b',
  '--theme-input-remove-color-dark': '#d34452',
  '--theme-input-remove-color-light': '#ea4c5b',
  '--theme-input-remove-color-lighter': '#ec5d6b',
  '--theme-input-remove-color-lightest': '#fac8ce',
  '--theme-input-background-color': '#f3f3f5',
  '--theme-input-disabled-background-color': '#cfcfcf',
  '--theme-input-focus-border-color': '#121327',

  '--theme-main-body-background-color': '#ffffff',
  '--theme-main-body-messages-color': '#121327',

  '--theme-modal-overlay-background-color': 'rgba(0, 0, 0, 0.4)',
  '--theme-modal-background-color': '#fafbfc',

  '--theme-nav-item-background-color': '#f3f3f5',
  '--theme-nav-item-background-color-hover': '#f9f9fa',
  '--theme-nav-item-background-color-active': '#fff',
  '--theme-nav-item-text-color': 'rgba(18, 19, 39, 0.6)',
  '--theme-nav-item-text-color-active': '#121327',

  '--theme-notification-message-background-color': 'rgba(218, 164, 154, 0.8)',
  '--theme-notification-message-text-color': '#fafbfc',

  '--theme-receive-qr-code-background-color': 'transparent',
  '--theme-receive-qr-code-foreground-color': '#121327',

  '--theme-send-confirmation-dialog-send-values-color': '#ea4c5b',

  '--theme-settings-body-background-color': '#ffffff',
  '--theme-settings-pane-background-color': '#f3f3f5',
  '--theme-settings-pane-border': '1px solid #f3f3f5',
  '--theme-settings-menu-box-background-color': '#f3f3f5',
  '--theme-settings-menu-box-border': '1px solid #f3f3f5',
  '--theme-settings-menu-item-text-color': '#121327',
  '--theme-settings-menu-item-text-color-active': '#121327',
  '--theme-settings-menu-item-text-color-enabled-hover': '#121327',
  '--theme-settings-menu-item-text-color-disabled': '#b3b3b3',
  '--theme-settings-menu-item-background-color-active': '#ffffff',
  '--theme-settings-menu-item-left-border-color-active': '#daa49a',
  '--theme-settings-theme-select-title-color': '#121327',

  '--theme-switch-background-color': '#daa49a',
  '--theme-switch-background-color-checked': '#daa49a',
  '--theme-switch-thumb-color-checked': '#fff',
  '--theme-switch-label-color': '#121327',

  '--theme-system-error-overlay-attention-icon-color': '#fafbfc',
  '--theme-system-error-overlay-background-color': 'rgba(171, 23, 0, 0.94)',
  '--theme-system-error-overlay-button-background-color': '#ab1700',
  '--theme-system-error-overlay-button-background-color-hover': '#fafbfc',
  '--theme-system-error-overlay-button-border-color': '#fafbfc',
  '--theme-system-error-overlay-button-text-color': '#fafbfc',
  '--theme-system-error-overlay-button-text-color-hover': '#ab1700',
  '--theme-system-error-overlay-text-color': '#fafbfc',

  '--theme-topbar-category-background-color-hover': '#373f52',
  '--theme-topbar-category-text-color': '#fafbfc',
  '--theme-topbar-background-color': '#373f52',
  '--theme-topbar-wallet-name-color': '#fafbfc',
  '--theme-topbar-wallet-info-color': '#fafbfc',
  '--theme-topbar-layout-body-background-color': '#ffffff',

  '--theme-transactions-list-background-color': '#f3f3f5',
  '--theme-transactions-list-border-color': '#f3f3f5',
  '--theme-transactions-list-group-date-color': '#121327',
  '--theme-transactions-list-item-details-color': '#121327',
  '--theme-transactions-card-background-color': '#e6ebf2',
  '--theme-transactions-card-income-background-color': '#e6ebf2',
  '--theme-transactions-card-expend-background-color': '#f2e6e6',
  '--theme-transactions-card-exchange-background-color': '#f2e6e6',
  '--theme-transactions-state-failed-background-color': '#bdc5ce',
  '--theme-transactions-state-failed-text-color': '#bdc5ce',
  '--theme-transactions-state-pending-background-color': '#bdc5ce',
  '--theme-transactions-state-pending-stripes-color': '#b2bac2',
  '--theme-transactions-priority-color': 'rgba(18, 19, 39, 0.6)',
  '--theme-transactions-priority-low-background-color': '#e8abbb',
  '--theme-transactions-priority-medium-background-color': '#e7d5a3',
  '--theme-transactions-priority-heigh-background-color': '#afdac2',
  '--theme-transactions-search-background-color': '#fafbfc',
  '--theme-transactions-icon-type-expend-background-color': '#54ca87',
  '--theme-transactions-icon-type-income-background-color': '#9ab2d9',
  '--theme-transactions-icon-type-exchange-background-color': '#10aca4',
  '--theme-transactions-icon-type-failed-background-color': '#eb6d7a',
  '--theme-transactions-sent-color': '#eb6d7a',
  '--theme-transactions-received-color': '#54ca87',

  '--theme-icon-nav-color': 'rgba(18, 19, 39, 0.6)',
  '--theme-icon-nav-color-active': '#ffffff',
  '--theme-icon-topbar-color': '#fafbfc',
  '--theme-icon-toggle-menu-color': '#fafbfc',
  '--theme-icon-ada-summary-wallet-amount-symbol-color': '#121327',
  '--theme-icon-ada-summary-wallet-pending-confirmation-symbol-color': '#121327',
  '--theme-icon-copy-address-color': '#121327',
  '--theme-icon-back-button-color': '#121327',
  '--theme-icon-close-button-color': '#121327',
  '--theme-icon-transactions-ada-symbol-color': '#121327',
  '--theme-icon-transaction-type-color': '#fafbfc',

  '--theme-backup-mnemonic-background-color': '#f3f3f5',

  '--theme-error-color': '#ea4c5b',
  '--theme-error-text-color': '#daa49a',

  '--theme-instructions-text-color': '#121327',

  '--theme-label-button-color': '#121327',

  '--theme-loading-background-color': '#fafbfc',

  '--theme-mnemonic-background-color': 'rgba(218, 164, 154, 0.12)',
  '--theme-mnemonic-background-color-hover': 'rgba(242, 183, 172, 0.12)',

  '--theme-separation-border-color': '#dfe4e8',

  '--theme-support-settings-text-color': '#121327',

  '--theme-terms-of-use-text-color': '#121327',

  '--theme-wallet-password-switch-label-color': '#121327',

  '--theme-banner-warning-background-color': '#b54b4b',
  '--theme-trezor-connect-dialog-middle-block-common-background-color': '#f3f3f5',
  '--theme-trezor-connect-dialog-middle-block-common-error-background-color': '#fdf1f0',

  '--theme-widgets-progress-step-common-color': '#daa49a',
};
