//  ==== Theme: Yoroi Renewed === //

export default {
  '--preferred-font': '"Times New Roman", serif',

  '--font-ultralight': 'Rubik-Light',
  '--font-thin': 'Rubik-Light',
  '--font-light': 'Rubik-Light',
  '--font-regular': 'Rubik-Regular',
  '--font-medium': 'Rubik-Medium',
  '--font-semibold': 'Rubik-Medium',
  '--font-bold': 'Rubik-Bold',
  '--font-heavy': 'Rubik-Bold',
  '--font-black': 'Rubik-Black',

  '--theme-input-hint-font': 'Rubik-Regular',
  '--theme-footer-text-font': 'Helvetica-Regular',

  '--theme-footer-background-color': '#fff',

  '--theme-scrollbar-thumb-background': '#c8ccce',

  '--theme-autocomplete-bg-color': '#f0f3f5',
  '--theme-autocomplete-border': '1px solid #9b9b9b',
  '--theme-autocomplete-border-focus-color': '#15d1aa',
  '--theme-autocomplete-search-color': '#353535',
  '--theme-autocomplete-placeholder-color': 'rgba(94, 96, 102, 0.5)',
  '--theme-autocomplete-selected-word-text-color': '#353535',
  '--theme-autocomplete-selected-word-box-background-color': '#f0f3f5',
  '--theme-autocomplete-focus-border-color': '#15d1aa',
  '--theme-autocomplete-hover-border-color': '#353535',
  '--theme-autocomplete-error-color': '#ea4c5b',

  '--theme-bordered-box-background-color': '#f0f3f5',
  '--theme-bordered-box-border': '1px solid #f0f3f5',
  '--theme-bordered-box-text-color': '#2b2c32',

  '--theme-button-primary-background-color': '#17d1aa',
  '--theme-button-primary-background-color-hover': '#17e2b8',
  '--theme-button-primary-background-color-active': '#12b190',
  '--theme-button-primary-background-color-disabled': '#c9ede5',
  '--theme-button-primary-text-color-disabled': '#ffffff',
  '--theme-button-primary-text-color': '#ffffff',

  '--theme-button-flat-background-color': 'rgba(218, 164, 154, 0.1)',
  '--theme-button-flat-background-color-hover': 'rgba(242, 183, 172, 0.1)',
  '--theme-button-flat-background-color-active': 'rgba(191, 144, 136, 0.1)',
  '--theme-button-flat-background-color-disabled': 'rgba(240, 243, 245, 0.3)',
  '--theme-button-flat-text-color-disabled': '#353535',
  '--theme-button-flat-text-color': '#353535',

  '--theme-button-outlined-background-color': '#15d1aa',
  '--theme-button-outlined-background-color-hover': 'rgba(23, 226, 184, 0.1)',
  '--theme-button-outlined-border-color-hover': 'rgb(23, 226, 184)',
  '--theme-button-outlined-background-color-active': '#12b190',
  '--theme-button-outlined-background-color-disabled': '#c9ede5',
  '--theme-button-outlined-text-color-disabled': '#c9ede5',
  '--theme-button-outlined-text-color': '#15d1aa',
  '--theme-button-outlined-active-text-color': '#ffffff',

  '--theme-checkbox-label-color': '#353535',
  '--theme-checkbox-border-color': '#353535',
  '--theme-checkbox-background-color-checked': '#17d1aa',

  '--theme-select-arrow-color': '#353535',
  '--theme-select-arrow-color-open': '#15d1aa',
  '--theme-select-background-color': '#ffffff',
  '--theme-select-option-highlight-color': '#edeeef',
  '--theme-select-option-text-color': '#353535',
  '--theme-select-options-border-color': '#ffffff',
  '--theme-select-options-shadow': 'none',

  '--theme-dialog-choice-tabs-text-color': '#353535',
  '--theme-dialog-choice-tabs-text-color-active': '#353535',
  '--theme-dialog-choice-tabs-bottom-border-color-active': '#353535',
  '--theme-dialog-big-button-background-color': '#f0f3f5',
  '--theme-dialog-big-button-border-color': '#f0f3f5',
  '--theme-dialog-big-button-label-color': '#353535',
  '--theme-dialog-big-button-description-color': '#353535',
  '--theme-dialog-title-color': '#2b2c32',

  '--theme-input-border-color': '#9b9b9b',
  '--theme-input-label-color': '#353535',
  '--theme-input-text-color': '#353535',
  '--theme-input-right-floating-text-color': 'rgba(94, 96, 102, 0.5)',
  '--theme-input-placeholder-color': 'rgba(94, 96, 102, 0.5)',
  '--theme-input-error-color': '#ea4c5b',
  '--theme-input-remove-color-dark': '#d34452',
  '--theme-input-remove-color-light': '#ea4c5b',
  '--theme-input-remove-color-lighter': '#ec5d6b',
  '--theme-input-remove-color-lightest': '#fac8ce',
  '--theme-input-background-color': '#f0f3f5',
  '--theme-input-disabled-background-color': '#cfcfcf',
  '--theme-input-focus-border-color': '#15d1aa',
  '--theme-input-hover-border-color': '#353535',

  '--theme-main-body-background-color': '#ffffff',
  '--theme-main-body-messages-color': '#353535',

  '--theme-modal-overlay-background-color': 'rgba(0, 0, 0, 0.4)',
  '--theme-modal-background-color': '#ffffff',

  '--theme-nav-item-background-color': '#f0f3f5',
  '--theme-nav-item-background-color-hover': '#f9f9fa',
  '--theme-nav-item-background-color-active': '#fff',
  '--theme-nav-item-text-color': '#adaeb6',
  '--theme-nav-item-text-color-active': '#2b2c32',

  '--theme-notification-message-background-color': 'rgba(21, 209, 170, 0.8)',
  '--theme-notification-message-text-color': '#fafbfc',
  '--theme-notification-message-receive-text-color': '#15d1aa',

  '--theme-receive-qr-code-background-color': 'transparent',
  '--theme-receive-qr-code-foreground-color': '#353535',

  '--theme-send-confirmation-dialog-send-values-color': '#15d1aa',
  '--theme-trezor-send-confirmation-info-block-background-color': '#f0f3f5',

  '--theme-topbar-category-background-color-hover': 'transparent',
  '--theme-topbar-category-text-color': '#ffffff',
  '--theme-topbar-background-color': 'linear-gradient(to right, #1e46bd, #4760ff)',
  '--theme-topbar-wallet-name-color': '#ffffff',
  '--theme-topbar-wallet-info-color': '#ffffff',
  '--theme-topbar-layout-body-background-color': '#ffffff',

  '--theme-transactions-list-background-color': '#f0f3f5',
  '--theme-transactions-list-border-color': '#f0f3f5',
  '--theme-transactions-list-group-date-color': '#2b2c32',
  '--theme-transactions-list-item-details-color': '#2b2c32',
  // '--theme-transactions-card-background-color': '#e6ebf2',
  // '--theme-transactions-card-income-background-color': '#e6ebf2',
  // '--theme-transactions-card-expend-background-color': '#f2e6e6',
  // '--theme-transactions-card-exchange-background-color': '#f2e6e6',
  // '--theme-transactions-state-failed-background-color': '#bdc5ce',
  // '--theme-transactions-state-failed-text-color': '#bdc5ce',
  // '--theme-transactions-state-pending-background-color': '#bdc5ce',
  // '--theme-transactions-state-pending-stripes-color': '#b2bac2',
  '--theme-transactions-priority-color': '#fff',
  '--theme-transactions-priority-low-background-color': 'rgba(250, 83, 128, 0.3)',
  // '--theme-transactions-priority-medium-background-color': '#e7d5a3',
  '--theme-transactions-priority-heigh-background-color': 'rgba(21, 209, 170, 0.5)',
  // '--theme-transactions-search-background-color': '#fafbfc',
  '--theme-transactions-icon-type-expend-background-color': '#15d1aa',
  // '--theme-transactions-icon-type-income-background-color': '#9ab2d9',
  // '--theme-transactions-icon-type-exchange-background-color': '#10aca4',
  // '--theme-transactions-icon-type-failed-background-color': '#eb6d7a',
  // '--theme-transactions-sent-color': '#eb6d7a',
  '--theme-transactions-received-color': '#15d1aa',

  // '--theme-icon-nav-color': 'rgba(18, 19, 39, 0.6)',
  // '--theme-icon-nav-color-active': '#ffffff',
  // '--theme-icon-topbar-color': '#fafbfc',
  // '--theme-icon-toggle-menu-color': '#fafbfc',
  // '--theme-icon-ada-summary-wallet-amount-symbol-color': '#121327',
  // '--theme-icon-ada-summary-wallet-pending-confirmation-symbol-color': '#121327',
  // '--theme-icon-copy-address-color': '#121327',
  // '--theme-icon-back-button-color': '#121327',
  // '--theme-icon-close-button-color': '#121327',
  '--theme-icon-transactions-ada-symbol-color': '#2b2c32',
  // '--theme-icon-transaction-type-color': '#fafbfc',

  '--theme-icon-nav-color': 'rgba(18, 19, 39, 0.6)',
  '--theme-icon-nav-color-active': '#ffffff',
  '--theme-icon-topbar-color': '#ffffff',
  '--theme-icon-toggle-menu-color': '#ffffff',
  '--theme-icon-ada-summary-wallet-amount-symbol-color': '#2b2c32',
  '--theme-icon-ada-summary-wallet-pending-confirmation-symbol-color': '#2b2c32',

  '--theme-wallet-add-color': '#ffffff',
  '--theme-wallet-add-translucent-color': 'rgba(255, 255, 255, 0.5)',
  '--theme-wallet-add-footer-text-color': '#353535',

  '--theme-error-color': '#ff1351',
  '--theme-error-text-color': '#ff1351',

  '--theme-instructions-text-color': '#adaeb6',
  '--theme-instructions-recovery-text-color': '#2b2c32',
  '--theme-password-condition-text-color': '#17d1aa',

  '--theme-label-button-color': '#353535',

  '--theme-terms-of-use-text-color': '#9b9b9b',

  '--theme-mnemonic-background-color': '#f0f3f5',
  '--theme-mnemonic-background-color-hover': '#f0f3f5',
  '--theme-mnemonic-border-color': '#9b9b9b',
  '--theme-mnemonic-border-filled-color': '#4a4a4a',
  '--theme-mnemonic-button-text-color': '#353535',

  '--theme-separation-border-color': '#dfe4e8',

  '--theme-banner-warning-background-color': '#f5a623',
  '--theme-trezor-connect-dialog-middle-block-common-background-color': '#ffffff',
  '--theme-trezor-connect-dialog-middle-block-common-error-background-color': '#ffffff',

  '--theme-widgets-progress-step-common-color': '#15d1aa',
};
