/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull extension'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 9
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest)
 *
 * [Full Setup Instructions](https://data.amplitude.com/emurgo/Yoroi/implementation/extension)
 */
import * as amplitude from '@amplitude/analytics-browser';
export type Environment = 'production' | 'development';
export declare const ApiKey: Record<Environment, string>;
/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export declare const DefaultConfiguration: BrowserOptions;
export interface LoadOptionsBase {
    disabled?: boolean;
}
export type LoadOptionsWithEnvironment = LoadOptionsBase & {
    environment: Environment;
    client?: {
        configuration?: BrowserOptions;
    };
};
export type LoadOptionsWithApiKey = LoadOptionsBase & {
    client: {
        apiKey: string;
        configuration?: BrowserOptions;
    };
};
export type LoadOptionsWithClientInstance = LoadOptionsBase & {
    client: {
        instance: BrowserClient;
    };
};
export type LoadOptions = LoadOptionsWithEnvironment | LoadOptionsWithApiKey | LoadOptionsWithClientInstance;
export interface ClaimAdaTransactionSettledProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    reward_amount?: number;
}
export interface ClaimAdaTransactionSubmittedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    reward_amount?: number;
}
export interface ConnectWalletDetailsSubmittedProperties {
    /**
     * The name of the hardware wallet.
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | Ledger, Trezor |
     */
    hardware_wallet?: "Ledger" | "Trezor";
}
export interface CreateWalletVerifyPhraseWordSelectedProperties {
    recovery_word_order?: any;
}
export interface DappPopupConnectWalletPageViewedProperties {
    /**
     * The total number of wallets that a user have.
     *  In case of not having any wallet, save 0 as the value.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    wallet_count: number;
}
export interface DappPopupSignTransactionSubmittedProperties {
    /**
     * Total ada value of every assets sent in the transaction
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    total_ada_value?: number;
}
export interface ExchangeSubmittedProperties {
    /**
     * The amount of ADA that the user will be exchanging.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    ada_amount?: number;
    /**
     * The type of ramp selected on a given transaction.
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | Buy, Sell |
     */
    ramp_type: "Buy" | "Sell";
}
export interface GovernanceChooseDrepPageViewedProperties {
    /**
     * This is the drep ID that the user inputs. This data can be obtained when the user opens the select a drep screen (a popup on extension and a bottom sheet on mobile) and inputting a drep ID.
     */
    drep_id?: string;
}
export interface GovernanceConfirmTransactionPageViewedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Enum Values | Delegate, Abstain, No Confidence |
     */
    governance_selection: "Delegate" | "Abstain" | "No Confidence";
}
export interface GovernanceTransactionSuccessPageViewedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Enum Values | Delegate, Abstain, No Confidence |
     */
    governance_selection: "Delegate" | "Abstain" | "No Confidence";
}
export interface GovernanceYoroiDRepSubmittedProperties {
    /**
     * This is the drep ID that the user inputs. This data can be obtained when the user opens the select a drep screen (a popup on extension and a bottom sheet on mobile) and inputting a drep ID.
     */
    drep_id?: string;
}
export interface InAppNotificationClosedProperties {
    type: string;
}
export interface InAppNotificationOpenedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Enum Values | tx_received, staking_rewards |
     */
    type?: "tx_received" | "staking_rewards";
}
export interface MidnightAirdropPageViewedProperties {
    /**
     * True if user has already claimed, false if user has not claimed
     */
    "is_claimed?"?: boolean;
    /**
     * True if user has eligible claim and false if not
     */
    "is_eligible?"?: boolean;
}
export interface NetworkSelectedProperties {
    /**
     * Current network
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | preprod, preview, mainnet, sancho |
     */
    from_network: "preprod" | "preview" | "mainnet" | "sancho";
    /**
     * Network selected
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | preprod, preview, mainnet, sancho |
     */
    to_network: "preprod" | "preview" | "mainnet" | "sancho";
}
export interface NftGalleryDetailsNavigationProperties {
    /**
     * Describe the navigation buttons on the NFT details view
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | Next, Previous |
     */
    nft_navigation: "Next" | "Previous";
}
export interface NftGalleryDetailsTabProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Enum Values | Overview, Metadata |
     */
    nft_tab: "Overview" | "Metadata";
}
export interface NftGalleryGridViewSelectedProperties {
    /**
     * Describe what type of grid is using the NFT gallery
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | 4_rows, 6_rows |
     */
    nft_grid_view?: "4_rows" | "6_rows";
}
export interface NftGalleryPageViewedProperties {
    /**
     * The total number of NFT's that an user have
     *
     * | Rule | Value |
     * |---|---|
     * | Type | integer |
     */
    nft_count: number;
}
export interface NftGallerySearchActivatedProperties {
    /**
     * The total number of NFT's that an user have
     *
     * | Rule | Value |
     * |---|---|
     * | Type | integer |
     */
    nft_count: number;
    /**
     * What user is looking to search on NFT gallery page
     */
    nft_search_term: string;
}
export interface PortfolioTokenDetailsProperties {
    /**
     * It show what tab from the Token details the user is.
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | Performance, Overview, Transactions |
     */
    token_details_tab: "Performance" | "Overview" | "Transactions";
}
export interface PortfolioTokensListPageViewedProperties {
    /**
     * It shows in what tab are we in the movile version of the Token list
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | Wallet Token, Dapps Token |
     */
    tokens_tab: "Wallet Token" | "Dapps Token";
}
export interface PortfolioTokensListSearchActivatedProperties {
    /**
     * What a user is looking to search.
     */
    search_term: string;
}
export interface ReceiveAmountGeneratedPageViewedProperties {
    /**
     * The amount of ADA that the user will be exchanging.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    ada_amount?: number;
}
export interface ReceiveCopyAddressClickedProperties {
    /**
     * Indicates the location of cop CTA
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | CTA Copy Address, Tap Address Details, Long Press wallet Address |
     */
    copy_address_location: "CTA Copy Address" | "Tap Address Details" | "Long Press wallet Address";
}
export interface RestoreWalletEnterPhraseStepStatusProperties {
    recovery_prhase_status: boolean;
}
export interface RestoreWalletEnterPhraseStepViewedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Enum Values | 15, 24 |
     */
    recovery_phrase_lenght: "15" | "24";
}
export interface SendSelectAssetSelectedProperties {
    /**
     * Total numbers of assets to be send
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    asset_count: number;
    /**
     * ```
     * nfts: [
     *      {
     *         nft_name: Bored Ape,
     *
     *       },
     *       {
     *         nft_name: Crypto Cats,
     *        }
     * ]
     * ```
     */
    nfts?: any[];
    /**
     * ```
     * Tokens: [
     *      {
     *         token_name: Ado,
     *         token_amount: '133',
     *       },
     *       {
     *         token_name: Ada,
     *         token_amount: '5',
     *        }
     * ]
     * ```
     */
    tokens?: any[];
}
export interface SendSelectAssetUpdatedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    asset_count: number;
    /**
     * ```
     * nfts: [
     *      {
     *         nft_name: Bored Ape,
     *
     *       },
     *       {
     *         nft_name: Crypto Cats,
     *        }
     * ]
     * ```
     */
    nfts?: any[];
    /**
     * ```
     * Tokens: [
     *      {
     *         token_name: Ado,
     *         token_amount: '133',
     *       },
     *       {
     *         token_name: Ada,
     *         token_amount: '5',
     *        }
     * ]
     * ```
     */
    tokens?: any[];
}
export interface SendSummaryPageViewedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    asset_count: number;
    /**
     * ```
     * nfts: [
     *      {
     *         nft_name: Bored Ape,
     *
     *       },
     *       {
     *         nft_name: Crypto Cats,
     *        }
     * ]
     * ```
     */
    nfts?: any[];
    /**
     * ```
     * Tokens: [
     *      {
     *         token_name: Ado,
     *         token_amount: '133',
     *       },
     *       {
     *         token_name: Ada,
     *         token_amount: '5',
     *        }
     * ]
     * ```
     */
    tokens?: any[];
}
export interface SendSummarySubmittedProperties {
    /**
     * The amount of ADA that the user will be exchanging.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    ada_amount?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    asset_count: number;
    /**
     * Total ada countervalue of the nfts sent
     */
    nft_ada_value?: string;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    nft_amount?: number;
    nft_name?: string;
    /**
     * ```
     * nfts: [
     *      {
     *         nft_name: Bored Ape,
     *
     *       },
     *       {
     *         nft_name: Crypto Cats,
     *        }
     * ]
     * ```
     */
    nfts?: any[];
    /**
     * Ada countervalue of the total tokens sent
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    token_ada_value?: number;
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    token_amount?: number;
    token_name?: string;
    /**
     * ```
     * Tokens: [
     *      {
     *         token_name: Ado,
     *         token_amount: '133',
     *       },
     *       {
     *         token_name: Ada,
     *         token_amount: '5',
     *        }
     * ]
     * ```
     */
    tokens?: any[];
}
export interface SettingsInAppNotificationsStatusUpdatedProperties {
    /**
     * | Rule | Value |
     * |---|---|
     * | Enum Values | enabled, disabled |
     */
    status?: "enabled" | "disabled";
}
export interface StakingCenterDelegationSubmittedProperties {
    /**
     * The amount of ADA that the user will be exchanging.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    ada_amount?: number;
    staking_pool?: string;
}
export interface SwapAssetFromChangedProperties {
    /**
     * Displaying the asset that the user chose to trade with.
     *
     * Asset Name Asset Ticker Policy ID
     *  \[
     *   {
     *     asset_name: 'ADA',
     *     asset_ticker: 'ADA',
     *     policy_id: '123456789'
     *   },
     * \]
     */
    from_asset: any[];
}
export interface SwapAssetToChangedProperties {
    /**
     * Displaying the asset that the user chose to trade to
     *
     * Asset Name
     * Asset Ticker
     * Policy ID
     */
    to_asset: any[];
}
export interface SwapCancelationSubmittedProperties {
    /**
     * The amount of asset that the user is swapping from
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    from_amount: number;
    /**
     * Displaying the asset that the user chose to trade with.
     *
     * Asset Name Asset Ticker Policy ID
     *  \[
     *   {
     *     asset_name: 'ADA',
     *     asset_ticker: 'ADA',
     *     policy_id: '123456789'
     *   },
     * \]
     *
     * | Rule | Value |
     * |---|---|
     * | Unique Items | null |
     */
    from_asset: any[];
    /**
     * The name of liquidity pool used for this swap transaction
     */
    pool_source: string;
    /**
     * The amount of asset that the user is swapping to
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    to_amount: number;
    /**
     * Displaying the asset that the user chose to trade to
     *
     * Asset Name
     * Asset Ticker
     * Policy ID
     *
     * | Rule | Value |
     * |---|---|
     * | Unique Items | null |
     */
    to_asset: any[];
}
export interface SwapConfirmedPageViewedProperties {
    /**
     * Define the tab that is active in the selected page
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | Open Orders, Completed Orders |
     */
    swap_tab?: "Open Orders" | "Completed Orders";
}
export interface SwapInitiatedProperties {
    /**
     * Displaying the asset that the user chose to trade with.
     *
     * Asset Name Asset Ticker Policy ID
     *  \[
     *   {
     *     asset_name: 'ADA',
     *     asset_ticker: 'ADA',
     *     policy_id: '123456789'
     *   },
     * \]
     *
     * | Rule | Value |
     * |---|---|
     * | Unique Items | null |
     */
    from_asset: any[];
    /**
     * The type of order selected on a given transaction
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | limit, market |
     */
    order_type: "limit" | "market";
    /**
     * The default slippage tolerance is 1%, but users are free to change the slippage.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    slippage_tolerance: number;
    /**
     * Displaying the asset that the user chose to trade to
     *
     * Asset Name
     * Asset Ticker
     * Policy ID
     *
     * | Rule | Value |
     * |---|---|
     * | Unique Items | null |
     */
    to_asset: any[];
}
export interface SwapOrderSelectedProperties {
    /**
     * The amount of asset that the user is swapping from
     */
    from_amount: string;
    /**
     * Displaying the asset that the user chose to trade with.
     *
     * Asset Name Asset Ticker Policy ID
     *  \[
     *   {
     *     asset_name: 'ADA',
     *     asset_ticker: 'ADA',
     *     policy_id: '123456789'
     *   },
     * \]
     */
    from_asset: any[];
    /**
     * The type of order selected on a given transaction
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | limit, market |
     */
    order_type?: "limit" | "market";
    /**
     * The name of liquidity pool used for this swap transaction
     */
    pool_source: string;
    /**
     * The default slippage tolerance is 1%, but users are free to change the slippage.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    slippage_tolerance?: number;
    /**
     * The amount of fees charged on the transaction. The value is in ADA.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    swap_fees?: number;
    /**
     * The amount of asset that the user is swapping to
     */
    to_amount: string;
    /**
     * Displaying the asset that the user chose to trade to
     *
     * Asset Name
     * Asset Ticker
     * Policy ID
     */
    to_asset: any[];
}
export interface SwapOrderSubmittedProperties {
    /**
     * The amount of asset that the user is swapping from
     */
    from_amount: string;
    /**
     * Displaying the asset that the user chose to trade with.
     *
     * Asset Name Asset Ticker Policy ID
     *  \[
     *   {
     *     asset_name: 'ADA',
     *     asset_ticker: 'ADA',
     *     policy_id: '123456789'
     *   },
     * \]
     */
    from_asset: any[];
    /**
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    from_asset_ada_value?: number;
    /**
     * The type of order selected on a given transaction
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | limit, market |
     */
    order_type?: "limit" | "market";
    /**
     * The name of liquidity pool used for this swap transaction
     */
    pool_source: string;
    /**
     * The default slippage tolerance is 1%, but users are free to change the slippage.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    slippage_tolerance?: number;
    /**
     * The amount of fees charged on the transaction. The value is in ADA.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    swap_fees?: number;
    /**
     * Cryptocurrency pairs being swapped (e.g., ADA to SNEK {ADA/SNEK}).
     */
    swap_pair?: string;
    /**
     * The amount of asset that the user is swapping to
     */
    to_amount: string;
    /**
     * Displaying the asset that the user chose to trade to
     *
     * Asset Name
     * Asset Ticker
     * Policy ID
     */
    to_asset: any[];
}
export interface SwapSlippageChangedProperties {
    /**
     * The default slippage tolerance is 1%, but users are free to change the slippage.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    slippage_tolerance: number;
}
export interface ThemeSelectedProperties {
    /**
     * The theme that is selected.
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | auto, light, dark |
     */
    theme: "auto" | "light" | "dark";
}
export interface SendProperties {
    /**
     * Total numbers of assets to be send
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    asset_count: number;
    /**
     * ```
     * nfts: [
     *      {
     *         nft_name: Bored Ape,
     *
     *       },
     *       {
     *         nft_name: Crypto Cats,
     *        }
     * ]
     * ```
     */
    nfts?: any[];
    /**
     * ```
     * Tokens: [
     *      {
     *         token_name: Ado,
     *         token_amount: '133',
     *       },
     *       {
     *         token_name: Ada,
     *         token_amount: '5',
     *        }
     * ]
     * ```
     */
    tokens?: any[];
}
export interface SwapProperties {
    /**
     * The amount of asset that the user is swapping from
     */
    from_amount: string;
    /**
     * Displaying the asset that the user chose to trade with.
     *
     * Asset Name Asset Ticker Policy ID
     *  \[
     *   {
     *     asset_name: 'ADA',
     *     asset_ticker: 'ADA',
     *     policy_id: '123456789'
     *   },
     * \]
     */
    from_asset: any[];
    /**
     * The type of order selected on a given transaction
     *
     * | Rule | Value |
     * |---|---|
     * | Enum Values | limit, market |
     */
    order_type?: "limit" | "market";
    /**
     * The name of liquidity pool used for this swap transaction
     */
    pool_source: string;
    /**
     * The default slippage tolerance is 1%, but users are free to change the slippage.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    slippage_tolerance?: number;
    /**
     * The amount of fees charged on the transaction. The value is in ADA.
     *
     * | Rule | Value |
     * |---|---|
     * | Type | number |
     */
    swap_fees?: number;
    /**
     * The amount of asset that the user is swapping to
     */
    to_amount: string;
    /**
     * Displaying the asset that the user chose to trade to
     *
     * Asset Name
     * Asset Ticker
     * Policy ID
     */
    to_asset: any[];
}
export declare class AllWalletsPageViewed implements BaseEvent {
    event_type: string;
}
export declare class AssetsPageViewed implements BaseEvent {
    event_type: string;
}
export declare class BuyAdaSuccessRedirect implements BaseEvent {
    event_type: string;
}
export declare class ClaimAdaPageViewed implements BaseEvent {
    event_type: string;
}
export declare class ClaimAdaTransactionSettled implements BaseEvent {
    event_properties?: ClaimAdaTransactionSettledProperties;
    event_type: string;
    constructor(event_properties?: ClaimAdaTransactionSettledProperties);
}
export declare class ClaimAdaTransactionSubmitted implements BaseEvent {
    event_properties?: ClaimAdaTransactionSubmittedProperties;
    event_type: string;
    constructor(event_properties?: ClaimAdaTransactionSubmittedProperties);
}
export declare class ConnectWalletCheckPageViewed implements BaseEvent {
    event_type: string;
}
export declare class ConnectWalletConnectPageViewed implements BaseEvent {
    event_type: string;
}
export declare class ConnectWalletDetailsPageViewed implements BaseEvent {
    event_type: string;
}
export declare class ConnectWalletDetailsSubmitted implements BaseEvent {
    event_properties?: ConnectWalletDetailsSubmittedProperties;
    event_type: string;
    constructor(event_properties?: ConnectWalletDetailsSubmittedProperties);
}
export declare class ConnectorPageViewed implements BaseEvent {
    event_type: string;
}
export declare class CreateWalletDetailsSettled implements BaseEvent {
    event_type: string;
}
export declare class CreateWalletDetailsStepViewed implements BaseEvent {
    event_type: string;
}
export declare class CreateWalletDetailsSubmitted implements BaseEvent {
    event_type: string;
}
export declare class CreateWalletLanguagePageViewed implements BaseEvent {
    event_type: string;
}
export declare class CreateWalletLearnPhraseStepViewed implements BaseEvent {
    event_type: string;
}
export declare class CreateWalletSavePhraseStepViewed implements BaseEvent {
    event_type: string;
}
export declare class CreateWalletSelectMethodPageViewed implements BaseEvent {
    event_type: string;
}
export declare class CreateWalletTermsPageViewed implements BaseEvent {
    event_type: string;
}
export declare class CreateWalletVerifyPhraseStepViewed implements BaseEvent {
    event_type: string;
}
export declare class CreateWalletVerifyPhraseWordSelected implements BaseEvent {
    event_properties?: CreateWalletVerifyPhraseWordSelectedProperties;
    event_type: string;
    constructor(event_properties?: CreateWalletVerifyPhraseWordSelectedProperties);
}
export declare class DappPopupAddCollateralPageViewed implements BaseEvent {
    event_type: string;
}
export declare class DappPopupConnectWalletPageViewed implements BaseEvent {
    event_properties: DappPopupConnectWalletPageViewedProperties;
    event_type: string;
    constructor(event_properties: DappPopupConnectWalletPageViewedProperties);
}
export declare class DappPopupConnectWalletPasswordPageViewed implements BaseEvent {
    event_type: string;
}
export declare class DappPopupSignTransactionPageViewed implements BaseEvent {
    event_type: string;
}
export declare class DappPopupSignTransactionSubmitted implements BaseEvent {
    event_properties?: DappPopupSignTransactionSubmittedProperties;
    event_type: string;
    constructor(event_properties?: DappPopupSignTransactionSubmittedProperties);
}
export declare class ExchangePageViewed implements BaseEvent {
    event_type: string;
}
export declare class ExchangeSubmitted implements BaseEvent {
    event_properties: ExchangeSubmittedProperties;
    event_type: string;
    constructor(event_properties: ExchangeSubmittedProperties);
}
export declare class GovernanceChooseDrepPageViewed implements BaseEvent {
    event_properties?: GovernanceChooseDrepPageViewedProperties;
    event_type: string;
    constructor(event_properties?: GovernanceChooseDrepPageViewedProperties);
}
export declare class GovernanceConfirmTransactionPageViewed implements BaseEvent {
    event_properties: GovernanceConfirmTransactionPageViewedProperties;
    event_type: string;
    constructor(event_properties: GovernanceConfirmTransactionPageViewedProperties);
}
export declare class GovernanceDashboardPageViewed implements BaseEvent {
    event_type: string;
}
export declare class GovernanceTransactionSuccessPageViewed implements BaseEvent {
    event_properties: GovernanceTransactionSuccessPageViewedProperties;
    event_type: string;
    constructor(event_properties: GovernanceTransactionSuccessPageViewedProperties);
}
export declare class GovernanceYoroiDRepSubmitted implements BaseEvent {
    event_properties?: GovernanceYoroiDRepSubmittedProperties;
    event_type: string;
    constructor(event_properties?: GovernanceYoroiDRepSubmittedProperties);
}
export declare class InAppNotificationClosed implements BaseEvent {
    event_properties: InAppNotificationClosedProperties;
    event_type: string;
    constructor(event_properties: InAppNotificationClosedProperties);
}
export declare class InAppNotificationOpened implements BaseEvent {
    event_properties?: InAppNotificationOpenedProperties;
    event_type: string;
    constructor(event_properties?: InAppNotificationOpenedProperties);
}
export declare class InAppNotificationViewed implements BaseEvent {
    event_type: string;
}
export declare class MidnightAirdropBannerCheckEligibility implements BaseEvent {
    event_type: string;
}
export declare class MidnightAirdropBannerClosed implements BaseEvent {
    event_type: string;
}
export declare class MidnightAirdropLeftMenuClicked implements BaseEvent {
    event_type: string;
}
export declare class MidnightAirdropPageViewed implements BaseEvent {
    event_properties?: MidnightAirdropPageViewedProperties;
    event_type: string;
    constructor(event_properties?: MidnightAirdropPageViewedProperties);
}
export declare class MidnightAirdropSignMessage implements BaseEvent {
    event_type: string;
}
export declare class NetworkSelected implements BaseEvent {
    event_properties: NetworkSelectedProperties;
    event_type: string;
    constructor(event_properties: NetworkSelectedProperties);
}
export declare class NftGalleryDetailsImageViewed implements BaseEvent {
    event_type: string;
}
export declare class NftGalleryDetailsNavigation implements BaseEvent {
    event_properties: NftGalleryDetailsNavigationProperties;
    event_type: string;
    constructor(event_properties: NftGalleryDetailsNavigationProperties);
}
export declare class NftGalleryDetailsPageViewed implements BaseEvent {
    event_type: string;
}
export declare class NftGalleryDetailsTab implements BaseEvent {
    event_properties: NftGalleryDetailsTabProperties;
    event_type: string;
    constructor(event_properties: NftGalleryDetailsTabProperties);
}
export declare class NftGalleryGridViewSelected implements BaseEvent {
    event_properties?: NftGalleryGridViewSelectedProperties;
    event_type: string;
    constructor(event_properties?: NftGalleryGridViewSelectedProperties);
}
export declare class NftGalleryPageViewed implements BaseEvent {
    event_properties: NftGalleryPageViewedProperties;
    event_type: string;
    constructor(event_properties: NftGalleryPageViewedProperties);
}
export declare class NftGallerySearchActivated implements BaseEvent {
    event_properties: NftGallerySearchActivatedProperties;
    event_type: string;
    constructor(event_properties: NftGallerySearchActivatedProperties);
}
export declare class OnboardingAnalyticsPageViewed implements BaseEvent {
    event_type: string;
}
export declare class PortfolioTokenDetails implements BaseEvent {
    event_properties: PortfolioTokenDetailsProperties;
    event_type: string;
    constructor(event_properties: PortfolioTokenDetailsProperties);
}
export declare class PortfolioTokensListPageViewed implements BaseEvent {
    event_properties: PortfolioTokensListPageViewedProperties;
    event_type: string;
    constructor(event_properties: PortfolioTokensListPageViewedProperties);
}
export declare class PortfolioTokensListSearchActivated implements BaseEvent {
    event_properties: PortfolioTokensListSearchActivatedProperties;
    event_type: string;
    constructor(event_properties: PortfolioTokensListSearchActivatedProperties);
}
export declare class ReceiveAmountGeneratedPageViewed implements BaseEvent {
    event_properties?: ReceiveAmountGeneratedPageViewedProperties;
    event_type: string;
    constructor(event_properties?: ReceiveAmountGeneratedPageViewedProperties);
}
export declare class ReceiveAmountPageViewed implements BaseEvent {
    event_type: string;
}
export declare class ReceiveCopyAddressClicked implements BaseEvent {
    event_properties: ReceiveCopyAddressClickedProperties;
    event_type: string;
    constructor(event_properties: ReceiveCopyAddressClickedProperties);
}
export declare class ReceiveGenerateNewAddressClicked implements BaseEvent {
    event_type: string;
}
export declare class ReceivePageListViewed implements BaseEvent {
    event_type: string;
}
export declare class ReceivePageViewed implements BaseEvent {
    event_type: string;
}
export declare class ReceiveShareAddressClicked implements BaseEvent {
    event_type: string;
}
export declare class RestoreWalletDetailsSettled implements BaseEvent {
    event_type: string;
}
export declare class RestoreWalletDetailsStepViewed implements BaseEvent {
    event_type: string;
}
export declare class RestoreWalletEnterPhraseStepStatus implements BaseEvent {
    event_properties: RestoreWalletEnterPhraseStepStatusProperties;
    event_type: string;
    constructor(event_properties: RestoreWalletEnterPhraseStepStatusProperties);
}
export declare class RestoreWalletEnterPhraseStepViewed implements BaseEvent {
    event_properties: RestoreWalletEnterPhraseStepViewedProperties;
    event_type: string;
    constructor(event_properties: RestoreWalletEnterPhraseStepViewedProperties);
}
export declare class RestoreWalletTypeStepViewed implements BaseEvent {
    event_type: string;
}
export declare class SellAdaInputAmount implements BaseEvent {
    event_type: string;
}
export declare class SellAdaSuccessRedirect implements BaseEvent {
    event_type: string;
}
export declare class SendInitiated implements BaseEvent {
    event_type: string;
}
export declare class SendSelectAssetPageViewed implements BaseEvent {
    event_type: string;
}
export declare class SendSelectAssetSelected implements BaseEvent {
    event_properties: SendSelectAssetSelectedProperties;
    event_type: string;
    constructor(event_properties: SendSelectAssetSelectedProperties);
}
export declare class SendSelectAssetUpdated implements BaseEvent {
    event_properties: SendSelectAssetUpdatedProperties;
    event_type: string;
    constructor(event_properties: SendSelectAssetUpdatedProperties);
}
export declare class SendSummaryPageViewed implements BaseEvent {
    event_properties: SendSummaryPageViewedProperties;
    event_type: string;
    constructor(event_properties: SendSummaryPageViewedProperties);
}
export declare class SendSummarySubmitted implements BaseEvent {
    event_properties: SendSummarySubmittedProperties;
    event_type: string;
    constructor(event_properties: SendSummarySubmittedProperties);
}
export declare class SettingsInAppNotificationsStatusUpdated implements BaseEvent {
    event_properties?: SettingsInAppNotificationsStatusUpdatedProperties;
    event_type: string;
    constructor(event_properties?: SettingsInAppNotificationsStatusUpdatedProperties);
}
export declare class SettingsPageViewed implements BaseEvent {
    event_type: string;
}
export declare class StakingCenterDelegationInitiated implements BaseEvent {
    event_type: string;
}
export declare class StakingCenterDelegationSubmitted implements BaseEvent {
    event_properties?: StakingCenterDelegationSubmittedProperties;
    event_type: string;
    constructor(event_properties?: StakingCenterDelegationSubmittedProperties);
}
export declare class StakingCenterPageViewed implements BaseEvent {
    event_type: string;
}
export declare class SwapAssetFromChanged implements BaseEvent {
    event_properties: SwapAssetFromChangedProperties;
    event_type: string;
    constructor(event_properties: SwapAssetFromChangedProperties);
}
export declare class SwapAssetToChanged implements BaseEvent {
    event_properties: SwapAssetToChangedProperties;
    event_type: string;
    constructor(event_properties: SwapAssetToChangedProperties);
}
export declare class SwapCancelationSubmitted implements BaseEvent {
    event_properties: SwapCancelationSubmittedProperties;
    event_type: string;
    constructor(event_properties: SwapCancelationSubmittedProperties);
}
export declare class SwapConfirmedPageViewed implements BaseEvent {
    event_properties?: SwapConfirmedPageViewedProperties;
    event_type: string;
    constructor(event_properties?: SwapConfirmedPageViewedProperties);
}
export declare class SwapInitiated implements BaseEvent {
    event_properties: SwapInitiatedProperties;
    event_type: string;
    constructor(event_properties: SwapInitiatedProperties);
}
export declare class SwapOrderSelected implements BaseEvent {
    event_properties: SwapOrderSelectedProperties;
    event_type: string;
    constructor(event_properties: SwapOrderSelectedProperties);
}
export declare class SwapOrderSubmitted implements BaseEvent {
    event_properties: SwapOrderSubmittedProperties;
    event_type: string;
    constructor(event_properties: SwapOrderSubmittedProperties);
}
export declare class SwapPoolChanged implements BaseEvent {
    event_type: string;
}
export declare class SwapSlippageChanged implements BaseEvent {
    event_properties: SwapSlippageChangedProperties;
    event_type: string;
    constructor(event_properties: SwapSlippageChangedProperties);
}
export declare class ThemeSelected implements BaseEvent {
    event_properties: ThemeSelectedProperties;
    event_type: string;
    constructor(event_properties: ThemeSelectedProperties);
}
export declare class TransactionsPageViewed implements BaseEvent {
    event_type: string;
}
export declare class VotingPageViewed implements BaseEvent {
    event_type: string;
}
export declare class WalletPageBuyBannerClicked implements BaseEvent {
    event_type: string;
}
export declare class WalletPageExchangeClicked implements BaseEvent {
    event_type: string;
}
export declare class WalletPageViewed implements BaseEvent {
    event_type: string;
}
export type PromiseResult<T> = {
    promise: Promise<T | void>;
};
export declare class Ampli {
    private disabled;
    private amplitude?;
    get client(): BrowserClient;
    get isLoaded(): boolean;
    private isInitializedAndEnabled;
    /**
     * Initialize the Ampli SDK. Call once when your application starts.
     *
     * @param options Configuration options to initialize the Ampli SDK with.
     */
    load(options: LoadOptions): PromiseResult<void>;
    /**
     * Identify a user and set user properties.
     *
     * @param userId The user's id.
     * @param options Optional event options.
     */
    identify(userId: string | undefined, options?: EventOptions): PromiseResult<Result>;
    /**
     * Flush the event.
     */
    flush(): PromiseResult<Result>;
    /**
     * Track event
     *
     * @param event The event to track.
     * @param options Optional event options.
     */
    track(event: Event, options?: EventOptions): PromiseResult<Result>;
    /**
     * All Wallets Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/All%20Wallets%20Page%20Viewed)
     *
     * This event tracks when a user views the All Wallets page on Menu. Note: only available on Yoroi Mobile.
     *
     * @param options Amplitude event options.
     */
    allWalletsPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Assets Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Assets%20Page%20Viewed)
     *
     * This event tracks when a user views the Assets page.
     *  On mobile  is available on the wallet page (First item from main menu) in the assets tab.
     *
     * @param options Amplitude event options.
     */
    assetsPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Buy Ada Success Redirect
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Buy%20Ada%20Success%20Redirect)
     *
     * This event tracks when a user is redirected to Yoroi after successfully buying ADA
     *
     * @param options Amplitude event options.
     */
    buyAdaSuccessRedirect(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Claim ADA Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Claim%20ADA%20Page%20Viewed)
     *
     * This event tracks when a user views the page to claim Claim /Transfer ADA page in Extension.
     *
     * You can find that page under Staking section.
     *
     * @param options Amplitude event options.
     */
    claimAdaPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Claim Ada Transaction Settled
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Claim%20Ada%20Transaction%20Settled)
     *
     * Event to track when a user successfully claims ADA and transaction is settled on chain
     *
     * @param properties The event's properties (e.g. reward_amount)
     * @param options Amplitude event options.
     */
    claimAdaTransactionSettled(properties?: ClaimAdaTransactionSettledProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Claim Ada Transaction Submitted
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Claim%20Ada%20Transaction%20Submitted)
     *
     * This Event to track when a user submits a transaction to claim ADA staking rewards.
     *
     * @param properties The event's properties (e.g. reward_amount)
     * @param options Amplitude event options.
     */
    claimAdaTransactionSubmitted(properties?: ClaimAdaTransactionSubmittedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Connect Wallet Check Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Connect%20Wallet%20Check%20Page%20Viewed)
     *
     * This event tracks when user chooses the connect hardware wallet option. This is the 1st step of the connect hardware wallet flow. In this page, the information about connecting a harware wallet is displayed to the user.
     *
     * @param options Amplitude event options.
     */
    connectWalletCheckPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Connect Wallet Connect Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Connect%20Wallet%20Connect%20Page%20Viewed)
     *
     * This event tracks when user connects the device and instructions are displayed. This is the 2nd step of the flow.
     *
     * @param options Amplitude event options.
     */
    connectWalletConnectPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Connect Wallet Details Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Connect%20Wallet%20Details%20Page%20Viewed)
     *
     * This event tracks when user accesses the enter wallet name page. This is the 3rd and final step of the flow
     *
     * @param options Amplitude event options.
     */
    connectWalletDetailsPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Connect Wallet Details Submitted
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Connect%20Wallet%20Details%20Submitted)
     *
     * This event captures the submission of the wallet name on the last step of the connecting a hardware wallet flow.
     *
     * @param properties The event's properties (e.g. hardware_wallet)
     * @param options Amplitude event options.
     */
    connectWalletDetailsSubmitted(properties?: ConnectWalletDetailsSubmittedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Connector Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Connector%20Page%20Viewed)
     *
     * This event tracks when a user views the dApp Connector page.
     *
     * @param options Amplitude event options.
     */
    connectorPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Create Wallet Details Settled
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Create%20Wallet%20Details%20Settled)
     *
     * When the wallet is created correctly. This event signifies the completion of the process of setting up wallet details during the creation of a new wallet
     *
     * @param options Amplitude event options.
     */
    createWalletDetailsSettled(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Create Wallet Details Step Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Create%20Wallet%20Details%20Step%20Viewed)
     *
     * This event tracks when a user views the details \*\*step 4\*\* while creating a wallet. User will introduce: \* Wallet Name \* Password \* Repeat Password
     *
     * @param options Amplitude event options.
     */
    createWalletDetailsStepViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Create Wallet Details Submitted
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Create%20Wallet%20Details%20Submitted)
     *
     * This event captures the submission of the wallet creation on the last step of the flow (\*\*step 4\*\*).
     *
     * @param options Amplitude event options.
     */
    createWalletDetailsSubmitted(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Create Wallet Language Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Create%20Wallet%20Language%20Page%20Viewed)
     *
     * This event tracks when a user views the page for selecting the language during the wallet creation process on the first time he launch Yoroi.
     *
     * @param options Amplitude event options.
     */
    createWalletLanguagePageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Create Wallet Learn Phrase Step Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Create%20Wallet%20Learn%20Phrase%20Step%20Viewed)
     *
     * This event tracks when a user view the \*\*first step\*\* of learn about recovery prhase
     *
     * @param options Amplitude event options.
     */
    createWalletLearnPhraseStepViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Create Wallet Save Phrase Step Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Create%20Wallet%20Save%20Phrase%20Step%20Viewed)
     *
     * This event tracks when a user views the \*\*second step\*\* to save their wallet recovery phrase during the wallet creation process
     *
     * @param options Amplitude event options.
     */
    createWalletSavePhraseStepViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Create Wallet Select Method Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Create%20Wallet%20Select%20Method%20Page%20Viewed)
     *
     * This event tracks when a user views the page where they can select the method to create a wallet:
     *
     * \* Create new wallet
     *
     * \* Restore existing wallet
     *
     * This event tracks when a user views the page where they can select the method to create a wallet\* Connect hardware wallet
     *
     * @param options Amplitude event options.
     */
    createWalletSelectMethodPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Create Wallet Terms Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Create%20Wallet%20Terms%20Page%20Viewed)
     *
     * This event tracks when a user views the terms of service agreement page on the creation wallet flow
     *
     * @param options Amplitude event options.
     */
    createWalletTermsPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Create Wallet Verify Phrase Step Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Create%20Wallet%20Verify%20Phrase%20Step%20Viewed)
     *
     * This event tracks when a user views the verification phrase step while creating a wallet
     *
     * @param options Amplitude event options.
     */
    createWalletVerifyPhraseStepViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Create Wallet Verify Phrase Word Selected
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Create%20Wallet%20Verify%20Phrase%20Word%20Selected)
     *
     * This event tracks the selection of a specific word during the process of verifying the recovery phrase when creating a wallet
     *
     * @param properties The event's properties (e.g. recovery_word_order)
     * @param options Amplitude event options.
     */
    createWalletVerifyPhraseWordSelected(properties?: CreateWalletVerifyPhraseWordSelectedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Dapp Popup Add Collateral Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Dapp%20Popup%20Add%20Collateral%20Page%20Viewed)
     *
     * This event tracks when a user views the "Add Collateral" page in the Dapp Connector Popup
     *
     * @param options Amplitude event options.
     */
    dappPopupAddCollateralPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Dapp Popup Connect Wallet Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Dapp%20Popup%20Connect%20Wallet%20Page%20Viewed)
     *
     * This event is triggered when the dapp connector popup is triggered and the user select the wallet that wants to connect.
     *
     * @param properties The event's properties (e.g. wallet_count)
     * @param options Amplitude event options.
     */
    dappPopupConnectWalletPageViewed(properties: DappPopupConnectWalletPageViewedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Dapp Popup Connect Wallet Password Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Dapp%20Popup%20Connect%20Wallet%20Password%20Page%20Viewed)
     *
     * This event tracks when a user attempts to connect their wallet by entering their password in the Dapp Connector popup
     *
     * @param options Amplitude event options.
     */
    dappPopupConnectWalletPasswordPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Dapp Popup Sign Transaction Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Dapp%20Popup%20Sign%20Transaction%20Page%20Viewed)
     *
     * This event tracks when a user loads a sign transaction screen on the dapp connector. Valid for extension and mobile.
     *
     * @param options Amplitude event options.
     */
    dappPopupSignTransactionPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Dapp Popup Sign Transaction Submitted
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Dapp%20Popup%20Sign%20Transaction%20Submitted)
     *
     * This event tracks the submission of a sign transaction request within the Dapp Connector screen. It's a Popup on extension and a full screen in Mobile.
     *
     * @param properties The event's properties (e.g. total_ada_value)
     * @param options Amplitude event options.
     */
    dappPopupSignTransactionSubmitted(properties?: DappPopupSignTransactionSubmittedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Exchange Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Exchange%20Page%20Viewed)
     *
     * This event tracks when a user loads the default state of the first step of the fiat on/off ramp on the new Banxa flow. That screen shows input ADA Amount, with the BUY ADA option selected by default.
     *
     * @param options Amplitude event options.
     */
    exchangePageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Exchange Submitted
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Exchange%20Submitted)
     *
     * This event tracks when a user clicks on "Proceed" in the Exchange page.
     *
     * @param properties The event's properties (e.g. ada_amount)
     * @param options Amplitude event options.
     */
    exchangeSubmitted(properties: ExchangeSubmittedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Governance Choose Drep Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Governance%20Choose%20Drep%20Page%20Viewed)
     *
     * This event tracks when user loads the bottom sheet on mobile or the popup on extension to introduce the Drep ID. To arrive to this page the user has to click on “Delegate to a Drep” section.
     *
     * @param properties The event's properties (e.g. drep_id)
     * @param options Amplitude event options.
     */
    governanceChooseDrepPageViewed(properties?: GovernanceChooseDrepPageViewedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Governance Confirm Transaction Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Governance%20Confirm%20Transaction%20Page%20Viewed)
     *
     * This event tracks when a user loads the confirm transaction page on the Governance flow. On Extension user would insert the password in that page. On extension user would do it in a bottom sheet afterwards.
     *
     * @param properties The event's properties (e.g. governance_selection)
     * @param options Amplitude event options.
     */
    governanceConfirmTransactionPageViewed(properties: GovernanceConfirmTransactionPageViewedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Governance Dashboard Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Governance%20Dashboard%20Page%20Viewed)
     *
     * This event tracks when a user loads the Governance Dashboard Page. The page is reached via the main navigation menu in extension and in the bottom menu icon on Extension.
     *
     * @param options Amplitude event options.
     */
    governanceDashboardPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Governance Transaction Success Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Governance%20Transaction%20Success%20Page%20Viewed)
     *
     * This event tracks when a user loads the success page at the end of the governance flow.
     *
     * @param properties The event's properties (e.g. governance_selection)
     * @param options Amplitude event options.
     */
    governanceTransactionSuccessPageViewed(properties: GovernanceTransactionSuccessPageViewedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Governance Yoroi DRep Submitted
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Governance%20Yoroi%20DRep%20Submitted)
     *
     * This event tracks when a user clicks the "Delegate to Yoroi DRep" button on the governance dashboard page.
     *
     * @param properties The event's properties (e.g. drep_id)
     * @param options Amplitude event options.
     */
    governanceYoroiDRepSubmitted(properties?: GovernanceYoroiDRepSubmittedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * In App Notification Closed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/In%20App%20Notification%20Closed)
     *
     * This event tracks when a user has manually closed a notification (not through the timer):
     *
     * * click on cross on extension
     *
     * * swipe on mobile
     *
     * @param properties The event's properties (e.g. type)
     * @param options Amplitude event options.
     */
    inAppNotificationClosed(properties: InAppNotificationClosedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * In App Notification Opened
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/In%20App%20Notification%20Opened)
     *
     * This event tracks when a user opens an in app notification:
     *
     * * click on extension
     *
     * * tap on mobile
     *
     * Type property indicates what type of in app notification it is - triggered by receiving a tx or because staking rewards are received.
     *
     * @param properties The event's properties (e.g. type)
     * @param options Amplitude event options.
     */
    inAppNotificationOpened(properties?: InAppNotificationOpenedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * In App Notification Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/In%20App%20Notification%20Viewed)
     *
     * This event tracks when an in app notification is displayed to the user.
     *
     * @param options Amplitude event options.
     */
    inAppNotificationViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Midnight Airdrop Banner Check Eligibility
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Midnight%20Airdrop%20Banner%20Check%20Eligibility)
     *
     * Event is triggered when a user triggers the banner redirection to the airdrop page by clicking on the CTA "check eligibility"
     *
     * @param options Amplitude event options.
     */
    midnightAirdropBannerCheckEligibility(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Midnight Airdrop Banner Closed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Midnight%20Airdrop%20Banner%20Closed)
     *
     * This events is triggered when the user dismisses the banner by cliking on the close CTA of the banner
     *
     * @param options Amplitude event options.
     */
    midnightAirdropBannerClosed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Midnight Airdrop Left Menu Clicked
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Midnight%20Airdrop%20Left%20Menu%20Clicked)
     *
     * This event is triggered when the user clicks on the airdrop entry point located in the left menu of extension
     *
     * @param options Amplitude event options.
     */
    midnightAirdropLeftMenuClicked(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Midnight Airdrop Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Midnight%20Airdrop%20Page%20Viewed)
     *
     * This event is triggered when the Airdrop page is displayed to the user
     *
     * @param properties The event's properties (e.g. is_claimed?)
     * @param options Amplitude event options.
     */
    midnightAirdropPageViewed(properties?: MidnightAirdropPageViewedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Midnight Airdrop Sign Message
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Midnight%20Airdrop%20Sign%20Message)
     *
     * Event is triggered once the user clicks on sign message of the sign message popup dispayed in the Airdrop funnel
     *
     * @param options Amplitude event options.
     */
    midnightAirdropSignMessage(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Network Selected
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Network%20Selected)
     *
     * Event to track when a user selects a network
     *
     * @param properties The event's properties (e.g. from_network)
     * @param options Amplitude event options.
     */
    networkSelected(properties: NetworkSelectedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * NFT Gallery Details Image Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/NFT%20Gallery%20Details%20Image%20Viewed)
     *
     * This event tracks when a user views the NFT image at full screen
     *
     * @param options Amplitude event options.
     */
    nftGalleryDetailsImageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * NFT Gallery Details Navigation
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/NFT%20Gallery%20Details%20Navigation)
     *
     * This event tracks when a use next and previous buttons to navigate across their NFTs. Note: available only on Extension.
     *
     * @param properties The event's properties (e.g. nft_navigation)
     * @param options Amplitude event options.
     */
    nftGalleryDetailsNavigation(properties: NftGalleryDetailsNavigationProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * NFT Gallery Details Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/NFT%20Gallery%20Details%20Page%20Viewed)
     *
     * This event tracks when a user views the details page of an NFT item.
     *
     * @param options Amplitude event options.
     */
    nftGalleryDetailsPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * NFT Gallery Details Tab
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/NFT%20Gallery%20Details%20Tab)
     *
     * This event tracks user interactions with the tab in the NFT Gallery details page. It provides insights into how users engage with specific details of NFTs, such as descriptions, attributes, or additional information
     *
     * @param properties The event's properties (e.g. nft_tab)
     * @param options Amplitude event options.
     */
    nftGalleryDetailsTab(properties: NftGalleryDetailsTabProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * NFT Gallery Grid View Selected
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/NFT%20Gallery%20Grid%20View%20Selected)
     *
     * This event is triggered when a user selects the grid view option in the NFT gallery
     *
     * @param properties The event's properties (e.g. nft_grid_view)
     * @param options Amplitude event options.
     */
    nftGalleryGridViewSelected(properties?: NftGalleryGridViewSelectedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * NFT Gallery Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/NFT%20Gallery%20Page%20Viewed)
     *
     * This event tracks when the NFT gallery it has loaded all nfts metadata
     *
     * @param properties The event's properties (e.g. nft_count)
     * @param options Amplitude event options.
     */
    nftGalleryPageViewed(properties: NftGalleryPageViewedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * NFT Gallery Search Activated
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/NFT%20Gallery%20Search%20Activated)
     *
     * User activates and starts a search in the NFT gallery. Delay of 0.5 seconds.
     *
     * @param properties The event's properties (e.g. nft_count)
     * @param options Amplitude event options.
     */
    nftGallerySearchActivated(properties: NftGallerySearchActivatedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Onboarding Analytics Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Onboarding%20Analytics%20Page%20Viewed)
     *
     * Event to track when a user views the onboarding analytics page.
     *
     * @param options Amplitude event options.
     */
    onboardingAnalyticsPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Portfolio Token Details
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Portfolio%20Token%20Details)
     *
     * When user visit the detailed information about a specific token within a user's portfolio. In mobile there's 3 tabs that would be implemented in different iterations.
     *
     * @param properties The event's properties (e.g. token_details_tab)
     * @param options Amplitude event options.
     */
    portfolioTokenDetails(properties: PortfolioTokenDetailsProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Portfolio Tokens List Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Portfolio%20Tokens%20List%20Page%20Viewed)
     *
     * Event to track when a user views the list of tokens in their portfolio.
     *
     * @param properties The event's properties (e.g. tokens_tab)
     * @param options Amplitude event options.
     */
    portfolioTokensListPageViewed(properties: PortfolioTokensListPageViewedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Portfolio Tokens List Search Activated
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Portfolio%20Tokens%20List%20Search%20Activated)
     *
     * This event tracks when a user activates and starts a search in the Tokens list page. Delay of 0.5 seconds.
     *
     * @param properties The event's properties (e.g. search_term)
     * @param options Amplitude event options.
     */
    portfolioTokensListSearchActivated(properties: PortfolioTokensListSearchActivatedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Receive Amount Generated Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Receive%20Amount%20Generated%20Page%20Viewed)
     *
     * When the bottom sheet or popup with a generated address with an specific amount is loaded
     *
     * @param properties The event's properties (e.g. ada_amount)
     * @param options Amplitude event options.
     */
    receiveAmountGeneratedPageViewed(properties?: ReceiveAmountGeneratedPageViewedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Receive Amount Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Receive%20Amount%20Page%20Viewed)
     *
     * When a user visit the page to insert specific amount of ADA that would be needed to generate a wallet address with that specific details.
     *
     * @param options Amplitude event options.
     */
    receiveAmountPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Receive Copy Address Clicked
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Receive%20Copy%20Address%20Clicked)
     *
     * When a user click on the any CTA to copy their address
     *
     * @param properties The event's properties (e.g. copy_address_location)
     * @param options Amplitude event options.
     */
    receiveCopyAddressClicked(properties: ReceiveCopyAddressClickedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Receive Generate New Address Clicked
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Receive%20Generate%20New%20Address%20Clicked)
     *
     * When a user click on the Generate new address button on the main receive page on the multiple address flow.
     *
     * @param options Amplitude event options.
     */
    receiveGenerateNewAddressClicked(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Receive Page List Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Receive%20Page%20List%20Viewed)
     *
     * When user has enabled multiple addresses and goes to the page where he can see the list of generated wallet addresses
     *
     * @param options Amplitude event options.
     */
    receivePageListViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Receive Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Receive%20Page%20Viewed)
     *
     * When user loads the Receive funds screen, where user can see their wallet address with a QR Code
     *
     * @param options Amplitude event options.
     */
    receivePageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Receive Share Address Clicked
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Receive%20Share%20Address%20Clicked)
     *
     * When a user click on the link to share the address
     *
     * @param options Amplitude event options.
     */
    receiveShareAddressClicked(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Restore Wallet Details Settled
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Restore%20Wallet%20Details%20Settled)
     *
     * This event captures the details of a wallet restoration process that has been successfully completed
     *
     * @param options Amplitude event options.
     */
    restoreWalletDetailsSettled(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Restore Wallet Details Step Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Restore%20Wallet%20Details%20Step%20Viewed)
     *
     * Track when user loads the page where user inserts wallet name and password
     *
     * @param options Amplitude event options.
     */
    restoreWalletDetailsStepViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Restore Wallet Enter Phrase Step Status
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Restore%20Wallet%20Enter%20Phrase%20Step%20Status)
     *
     * This events tracks the validation of the recovery phrase is verified, once the user insert the latest word. The output can be positive or negative and we do save that in he property: recovery*prhase*status
     *
     * @param properties The event's properties (e.g. recovery_prhase_status)
     * @param options Amplitude event options.
     */
    restoreWalletEnterPhraseStepStatus(properties: RestoreWalletEnterPhraseStepStatusProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Restore Wallet Enter Phrase Step Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Restore%20Wallet%20Enter%20Phrase%20Step%20Viewed)
     *
     * This event tracks when a user views the step to enter the recovery phrase while restoring a wallet (**Step 2**).
     *
     * @param properties The event's properties (e.g. recovery_phrase_lenght)
     * @param options Amplitude event options.
     */
    restoreWalletEnterPhraseStepViewed(properties: RestoreWalletEnterPhraseStepViewedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Restore Wallet Type Step Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Restore%20Wallet%20Type%20Step%20Viewed)
     *
     * This event tracks when a user views the **first step after** selecting restore wallet, were they have to choose between:
     *
     * * 15-word recovery phrase
     *
     * * 24-word recovery phrase
     *
     * @param options Amplitude event options.
     */
    restoreWalletTypeStepViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Sell Ada Input Amount
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Sell%20Ada%20Input%20Amount)
     *
     * Event to track when user starts the Sell ada flow so after selecting the sell option and having to input amount of ADA to sell
     *
     * @param options Amplitude event options.
     */
    sellAdaInputAmount(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Sell Ada Success Redirect
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Sell%20Ada%20Success%20Redirect)
     *
     * This event tracks when a user is redirected to Yoroi after successfully selling ADA
     *
     * @param options Amplitude event options.
     */
    sellAdaSuccessRedirect(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Send Initiated
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Send%20Initiated)
     *
     * This event tracks when a user loads the default state of the first step of the multiasset transaction flow. That screen shows receiver address and optional memo
     *
     * @param options Amplitude event options.
     */
    sendInitiated(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Send Select Asset Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Send%20Select%20Asset%20Page%20Viewed)
     *
     * This event tracks when a user views the "Amount" page in the send flow.
     *
     * @param options Amplitude event options.
     */
    sendSelectAssetPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Send Select Asset Selected
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Send%20Select%20Asset%20Selected)
     *
     * When a user click "next" on the send flow: "Amount" step on extension / "Assets added" in mobile
     *
     * @param properties The event's properties (e.g. asset_count)
     * @param options Amplitude event options.
     */
    sendSelectAssetSelected(properties: SendSelectAssetSelectedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Send Select Asset Updated
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Send%20Select%20Asset%20Updated)
     *
     * When an user update the tokens selection on "amount" step:
     *  \- Add
     *  \- Remove
     *  \- Updated
     *
     * @param properties The event's properties (e.g. asset_count)
     * @param options Amplitude event options.
     */
    sendSelectAssetUpdated(properties: SendSelectAssetUpdatedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Send Summary Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Send%20Summary%20Page%20Viewed)
     *
     * When a user loads the Preview page (Could be called comfirmation too) on the send flow.
     *
     * @param properties The event's properties (e.g. asset_count)
     * @param options Amplitude event options.
     */
    sendSummaryPageViewed(properties: SendSummaryPageViewedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Send Summary Submitted
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Send%20Summary%20Submitted)
     *
     * When a user click "send" on the "Preview" step on the send flow.
     *
     * @param properties The event's properties (e.g. ada_amount)
     * @param options Amplitude event options.
     */
    sendSummarySubmitted(properties: SendSummarySubmittedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Settings In App Notifications Status Updated
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Settings%20In%20App%20Notifications%20Status%20Updated)
     *
     * This event tracks when a user edits the in app notification setting by disabling or enabling in app notifications.
     *
     * @param properties The event's properties (e.g. status)
     * @param options Amplitude event options.
     */
    settingsInAppNotificationsStatusUpdated(properties?: SettingsInAppNotificationsStatusUpdatedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Settings Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Settings%20Page%20Viewed)
     *
     * This event tracks when a user views the settings page within the application.
     *
     * @param options Amplitude event options.
     */
    settingsPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Staking Center Delegation Initiated
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Staking%20Center%20Delegation%20Initiated)
     *
     * Event to track when a user initiates the delegation process in the Staking Center, accessing the delegate modal after selecting a pool
     *
     * @param options Amplitude event options.
     */
    stakingCenterDelegationInitiated(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Staking Center Delegation Submitted
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Staking%20Center%20Delegation%20Submitted)
     *
     * Event indicating that a user has submitted a delegation in the staking center.
     *
     * @param properties The event's properties (e.g. ada_amount)
     * @param options Amplitude event options.
     */
    stakingCenterDelegationSubmitted(properties?: StakingCenterDelegationSubmittedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Staking Center Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Staking%20Center%20Page%20Viewed)
     *
     * This event tracks when a user views the Staking Center page on Staking menu.
     *
     * @param options Amplitude event options.
     */
    stakingCenterPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Swap Asset From Changed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Swap%20Asset%20From%20Changed)
     *
     * When user changed the selected asset on "From" section
     *
     * Owner: Omar Rozak
     *
     * @param properties The event's properties (e.g. from_asset)
     * @param options Amplitude event options.
     */
    swapAssetFromChanged(properties: SwapAssetFromChangedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Swap Asset To Changed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Swap%20Asset%20To%20Changed)
     *
     * When user changed the selected asset on "To" section
     *
     * Owner: Omar Rozak
     *
     * @param properties The event's properties (e.g. to_asset)
     * @param options Amplitude event options.
     */
    swapAssetToChanged(properties: SwapAssetToChangedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Swap Cancelation Submitted
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Swap%20Cancelation%20Submitted)
     *
     * When user sign a transaction to cancel the swap order
     *
     * Owner: Omar Rozak
     *
     * @param properties The event's properties (e.g. from_amount)
     * @param options Amplitude event options.
     */
    swapCancelationSubmitted(properties: SwapCancelationSubmittedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Swap Confirmed  Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Swap%20Confirmed%20%20Page%20Viewed)
     *
     * When the user opens Completed Order page
     *
     * Owner: Omar Rozak
     *
     * @param properties The event's properties (e.g. swap_tab)
     * @param options Amplitude event options.
     */
    swapConfirmedPageViewed(properties?: SwapConfirmedPageViewedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Swap Initiated
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Swap%20Initiated)
     *
     * When user clicks on the swap feature and sees the default state of the swap.
     *
     * Owner: Omar Rozak
     *
     * @param properties The event's properties (e.g. from_asset)
     * @param options Amplitude event options.
     */
    swapInitiated(properties: SwapInitiatedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Swap Order Selected
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Swap%20Order%20Selected)
     *
     * When user click on "swap" button after selecting asset from, entering the amount of asset form, selecting asset to, entering amount of asset to, and choosing a pool
     *
     * Owner: Omar Rozak
     *
     * @param properties The event's properties (e.g. from_amount)
     * @param options Amplitude event options.
     */
    swapOrderSelected(properties: SwapOrderSelectedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Swap Order Submitted
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Swap%20Order%20Submitted)
     *
     * When user click confirm on the check out page, after entering their spending password
     *
     * Owner: Omar Rozak
     *
     * @param properties The event's properties (e.g. from_amount)
     * @param options Amplitude event options.
     */
    swapOrderSubmitted(properties: SwapOrderSubmittedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Swap Pool Changed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Swap%20Pool%20Changed)
     *
     * When user clicked a different pool on the "Select Pool" page
     *
     * Owner: Sergio SF
     *
     * @param options Amplitude event options.
     */
    swapPoolChanged(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Swap Slippage Changed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Swap%20Slippage%20Changed)
     *
     * When user click apply on the swap setting page
     *
     * Owner: Omar Rozak
     *
     * @param properties The event's properties (e.g. slippage_tolerance)
     * @param options Amplitude event options.
     */
    swapSlippageChanged(properties: SwapSlippageChangedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Theme Selected
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Theme%20Selected)
     *
     * This event is triggrered when a user had selected a theme.
     *
     * @param properties The event's properties (e.g. theme)
     * @param options Amplitude event options.
     */
    themeSelected(properties: ThemeSelectedProperties, options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Transactions Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Transactions%20Page%20Viewed)
     *
     * This event tracks when a user views the transactions page within the wallet. On mobile is available on the wallet page (First item from main navigation item) in the transactions tab.
     *
     * @param options Amplitude event options.
     */
    transactionsPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Voting Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Voting%20Page%20Viewed)
     *
     * This event tracks when a user views the Catalyst Voting page.
     *
     * @param options Amplitude event options.
     */
    votingPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Wallet Page Buy Banner Clicked
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Wallet%20Page%20Buy%20Banner%20Clicked)
     *
     * This event tracks when a user clicks on "Buy Button" on the Wallet Page’s BUY ADA banner.
     *
     * This banner only appears for **new users** or those **users that has 0 ADA** Balance.
     *
     * @param options Amplitude event options.
     */
    walletPageBuyBannerClicked(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Wallet Page Exchange Clicked
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Wallet%20Page%20Exchange%20Clicked)
     *
     * This event tracks when a user clicks on "Buy" on the Wallet Page.
     *
     * @param options Amplitude event options.
     */
    walletPageExchangeClicked(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
    /**
     * Wallet Page Viewed
     *
     * [View in Tracking Plan](https://data.amplitude.com/emurgo/Yoroi/events/main/latest/Wallet%20Page%20Viewed)
     *
     * Wallet page is the default page when the user logs into the app and selects the wallet that is going to be using (Once the initial setup is done)
     *
     * @param options Amplitude event options.
     */
    walletPageViewed(options?: EventOptions): PromiseResult<amplitude.Types.Result>;
}
export declare const ampli: Ampli;
type BrowserOptions = amplitude.Types.BrowserOptions;
export type BrowserClient = amplitude.Types.BrowserClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type IdentifyEvent = amplitude.Types.IdentifyEvent;
export type GroupEvent = amplitude.Types.GroupIdentifyEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
export {};
