name: E2E Test Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review]
  pull_request_review:
    types: [submitted]

jobs:
  Build-Extension:
    if: github.event.review && (github.event.review.state == 'approved' || contains(github.event.review.body, '/check') || contains(github.event.review.body, '/ext-general') || contains(github.event.review.body, '/ext-failing'))
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: npm install
        run: |
          . install-all.sh

      - name: Build the test mainnet version
        working-directory: ./packages/yoroi-extension
        run: npm run test:build:mainnet

      - name: Archive built app
        uses: actions/upload-artifact@v4
        with:
          name: builtApp
          path: |
            ./packages/yoroi-extension/Yoroi-test.crx
            ./packages/yoroi-extension/Yoroi.xpi
          retention-days: 1
          overwrite: true
