name: Lint branch name and add jira task 

on:
  push:
    branches:
      - develop
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  # A script to ensure that the PR branch name is named following the new naming
  # conventions `<tag>/<jira-ticket>/<short-summary>` and to make a comment with
  # the Jira ticket associated with the open PR
  # Script: https://github.com/AhmedIbrahim336/jira-ticket
  jira: 
    runs-on: ubuntu-latest
    steps: 
      - run: curl ${{ secrets.JIRA_TICKET_API }}${{ github.event.number }}
