name: Link JIRA

on:
  push:
    branches:
      - develop
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  jira: 
    runs-on: ubuntu-latest
    name: Auto jira link
    steps:
      - name: Comment PR
        uses: sbimochan/jira-link-commenter@v2.4
        with:
          jira-project-url: ${{ secrets.JIRA_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
