on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: packages/yoroi-extension

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: npm install
        run: |
          npm i --legacy-peer-deps 
          npm i --legacy-peer-deps --prefix packages/yoroi-extension 

      - name: Build
        run: |
          cd packages/yoroi-extension
          npm run keygen && mv key.pem production-key.pem && npm run prod:stable

      - name: Install Octopus CLI 
        uses: OctopusDeploy/install-octopus-cli-action@v1.1.8
        with:
          version: latest

      - name: Move package file 
        run: mv "packages/yoroi-extension/Yoroi.zip" yoroi-frontend.${{ steps.package-version.outputs.current-version}}-production.zip

      - name: Push package to Octopus Deploy 
        uses: OctopusDeploy/push-package-action@v1.0.1
        with:
          packages: 'yoroi-frontend.${{ steps.package-version.outputs.current-version}}-production.zip'
          server: https://emurgo.octopus.app
          api_key: ${{ secrets.OCTOPUS_API_KEY }}

      - name: Create release 
        uses: OctopusDeploy/create-release-action@v1.1.3
        with:
          server: https://emurgo.octopus.app
          api_key: ${{ secrets.OCTOPUS_API_KEY }}
          project: 'yoroi-frontend'
          channel: 'Production'
          packages: 'yoroi-frontend:${{ steps.package-version.outputs.current-version}}-production'
          release_number: '${{ steps.package-version.outputs.current-version}}-production'
