on:
  push:
    tags:
      - '*'

jobs:
  push-to-octopus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      - name: Zip package 📦
        run: (cd . && zip -r ../yoroi-frontend-smoke-builds.${{ github.ref_name }}.zip ./* ./.??*)
        
      - name: Install Octopus CLI 🐙
        uses: OctopusDeploy/install-octopus-cli-action@v3
        with:
          version: latest

      - name: Push package to Octopus Deploy 🐙
        uses: OctopusDeploy/push-package-action@v3
        env: 
          OCTOPUS_URL: https://emurgo.octopus.app
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
          OCTOPUS_SPACE: 'DevOps'
        with:
          packages: '../yoroi-frontend-smoke-builds.${{ github.ref_name }}.zip'

      - name: Create release 
        uses: OctopusDeploy/create-release-action@v3
        env: 
          OCTOPUS_URL: https://emurgo.octopus.app
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
          OCTOPUS_SPACE: 'DevOps'
        with:
          project: yoroi-frontend-smoke-builds
          channel: 'Dev'
          packages: 'yoroi-frontend-smoke-builds:${{ github.ref_name }}'
          release_number: '${{ github.ref_name }}'
